### PR TITLE
Fix some commands with quoting issues (I guess)

### PR DESCRIPTION
**Pull request by WalkerOfBacon**
image

### CODE REVIEW

**Comment by watameln** [comment]
do not merge i will kill you if you merge

**Comment by WalkerOfBacon** [comment]
> do not merge i will kill you if you merge

hating
(being fr whats wrong)

**Comment by watameln** [comment]
> > do not merge i will kill you if you merge
> 
> hating (being fr whats wrong)

i got teams with "word" in them 😭

**Comment by WalkerOfBacon** [comment]
> i got teams with "word" in them 😭
oh-

**Pull request closed without merging**
