### PR TITLE
Fix regression introduced in #1308

### PR DESCRIPTION
**Pull request by ccuser44**
Fix regression introduced in #1308

### CODE REVIEW

**Comment by Dimenpsyonal** [comment]
Why is this two PRs

**Comment by Dimenpsyonal** [comment]
Put them in the same PR smh smh

**Comment by ccuser44** [comment]
> Put them in the same PR smh smh

No because both PRs are totally different and serve different purposes

**Comment by Dimenpsyonal** [comment]
No because they are both reversions

**Comment by ccuser44** [comment]
> No because they are both reversions

Done in #1308

**Pull request closed without merging**
