### PR TITLE
Made Yuenliang compiler work with Luau code

### PR DESCRIPTION
**Pull request by ccuser44**
Features added:

- Luau string literals `\x` for hex literals, `\u` UTF8 string literals, `\z` string literal
- Luau number support, binary number constants `0b01010101010` and `0B01010101010`, Luau intiger constants decimal seperators
- Luau compound operators
- Luau continue statement

Limitations
- Doesn't work with type annotations (Too hard to implement)
- `continue` statement is always a keyword, doesn't make much sense to add backwards compatibility, would overcomplicate the parser, also encourages bad practice of using `continue` as a non-keyword

### CODE REVIEW

**Comment by LolloDev5123** [comment]
Beautiful pull request.

**Comment by Sceleratis** [comment]
1373 │   luaK:codeAsBx(fs, "OP_JMP", 0, INSERTTHELOOPINSTRUCTIONOFFSETHERE) -- // Is bl.breaklist.previous the loop instruction? I have to test

**Comment by Sceleratis** [comment]
Unintentionally demarked for review so ignore that lol

**Comment by ccuser44** [comment]
> Unintentionally marked for review so ignore that lol

This pull is not ready ywt, Ill still add compound operators

**Comment by LolloDev5123** [comment]
Nice, you should contribute these changes to the original module repo?

**Comment by ccuser44** [comment]
> Nice, you should contribute these changes to the original module repo?

There isn't an original repo per say, the original repo is the defunct project Yuenliang which is made to be a Lua in Lua vm. Not a Luau compiler

**Review by P3tray — APPROVED** [review]
i merely scrolled though it and admired the glory

**Comment by P3tray** [comment]
> > Nice, you should contribute these changes to the original module repo?
> 
> There isn't an original repo per say, the original repo is the defunct project Yuenliang which is made to be a Lua in Lua vm. Not a Luau compiler

When can merge?

also https://gist.github.com/Rerumu/ecaf1de2f2b31d0fa91b9bac8e1e15d8 might be helpful for you idk

**Comment by P3tray** [comment]
juding by the new commits this is ready to merge

ale is cursed by the never merging commits

**Comment by P3tray** [comment]
im not going to review this

**Comment by Sceleratis** [comment]
anyone know what the state of this PR is

**Comment by LolloDev5123** [comment]
> This pull is not ready yet, Ill still add compound operators
And from the recent commits, it looks like @ccuser44 is working on the compound operators; but he's inactive as of now

**Comment by LiveFireExercise** [comment]
wake up ccuser44

**Comment by P3tray** [comment]
Mr. PNG, wake up.

**Comment by LiveFireExercise** [comment]
wake up dr freeman

**Comment by watameln** [comment]
wake up and smell the ashes

**Comment by P3tray** [comment]
gordong

**Comment by LolloDev5123** [comment]
What about support for non binary integers you bigot

**Comment by LiveFireExercise** [comment]
this pull has been open for 1 year and 2 months, and 5 days today. either close it or merge it. please

**Comment by P3tray** [comment]
please merge <3

**Comment by P3tray** [comment]
NO WAY

**Comment by WalkerOfBacon** [comment]
real merge

**Comment by jLn0n** [comment]
why merge when continue keyword isn't finished yet

**Comment by LiveFireExercise** [comment]
Yet another ccuser failure...

**Comment by moo1210** [comment]
yeah this pr also bricks loadstring from running altogether in certain instances, my bug fix pr will fix that soon.

**Comment by watameln** [comment]
image
stop sending me emails

**Comment by LiveFireExercise** [comment]
No way!!! A hitman 3 modding thread

**Comment by watameln** [comment]
i would like to test this feature if it doesnt work then im gonna be sad

**Comment by P3tray** [comment]
> why merge when continue keyword isn't finished yet

nobody uses that ever

**Comment by P3tray** [comment]
> yeah this pr also bricks loadstring from running altogether in certain instances, my bug fix pr will fix that soon.

unsuprising

**Pull request merged**
