### PR TITLE
Dex API dump update

### PR DESCRIPTION
**Pull request by DrewBokman**
Updates the Dex Api Dump.

### CODE REVIEW

**Review by P3tray — COMMENTED** [review]
Who the hell is gonna read the 96,320 line dex update? God damn this is hidden malware city, no offense to you Drew.

**Comment by DrewBokman** [comment]
99% of it is a long string of the api dump

**Comment by DrewBokman** [comment]
I can minify it if needed.

**Comment by karl-police** [comment]
Import the JSON correctly next time pls :(

**Pull request merged**
