### PR TITLE
Remove all commented github links

### PR DESCRIPTION
**Pull request by LiveFireExercise**

### CODE REVIEW

**Comment by watameln** [comment]
amazing

**Comment by ccuser44** [comment]
Don't remove them fully just remove the `.com` part

**Comment by LiveFireExercise** [comment]
> Don't remove them fully just remove the `.com` part and the `https://` parts

that's so petty. i love it

**Comment by karl-police** [comment]
Is this because of Roblox

**Comment by Sceleratis** [comment]
conflicting with my mental health

**Comment by ccuser44** [comment]
> > Don't remove them fully just remove the .com part and the https:// parts
> 
> that's so petty. i love it

No you should really do it because otherwise they would be totally gone, meanwhile if you only removed the `https://` and `.com` parts then the github ones would still be there but not break roblox TOS

**Comment by LiveFireExercise** [comment]
me too

**Pull request merged**
