### PR TITLE
Update cool person's name

### PR DESCRIPTION
**Pull request by LiveFireExercise**

### CODE REVIEW

**Comment by LiveFireExercise** [comment]
> i agree
> 
> very cool person mrrp meow

- 🐱

**Review by WalkerOfBacon — APPROVED** [review]
epic

**Comment by NoobBucket** [comment]
you forgot my name 🤡

**Comment by LiveFireExercise** [comment]
> you forgot my name 🤡

:p

**Review by ccuser44 — APPROVED** [review]

**Pull request merged**
