### PR TITLE
[Big bugfix&improvement pack]: Fixes many annoying bugs

### LINKED ISSUE #1555: The ping values ​​are different.
### Version channel

Stable (Default)

### Loader version

_No response_

### What part of Adonis is this related to?

Loader/Settings

### What happened?

The ping value displayed by Adonis' !ping is different from the ping value displayed in Roblox's performance status.
I'm Japanese and I use Google Translate.

image

### Device

Windows

### Relevant log output

_No response_

### LINKED ISSUE #1574: Audio player does not skip to next track upon current one finishing
### What part of Adonis is this related to?

Loader/Settings

### What are you suggesting?

Im referring to the audio player that appears with command !ap
It doesnt skip to next track if i finish one, this also makes the "shuffle" option useless.
Should be a simple fix!

### LINKED ISSUE #1578: || ADONIS SUGGESTION || Allow personal stats viewing
### What part of Adonis is this related to?

Command

### What are you suggesting?

In games that has strict admin rules, like rostores, you couldn't see your own admin only stats, so why not allow personal stats viewing?

This is current
image

### LINKED ISSUE #1600: Text chat commands are autocompleted to all users, including users without mod/admin
### Version channel

Stable (Default)

### Loader version

260

### What part of Adonis is this related to?

Command

### What happened?

When I type a command in the chat (if the game uses `TextChatService`), it *would* be expected that whitelisted users should only be able to see the command and not normal users without moderator/admin. However, this is not the case.

Users, even if they **aren't** whitelisted, are able to see **all** commands in Adonis in chat by just typing /. This is very annoying for normal users, because they may want to type something like `/e dance2` but they are unable to because of the number of commands that show up in autocomplete.

## Why does this happen?
I've actually tracked the issue down, and I've found the source of the issue:

When text chat commands are created by Adonis, they are created without *ever* touching anything related to [AutocompleteVisible](https://robloxapi.github.io/ref/class/TextChatCommand.html#member-AutocompleteVisible). Due to this, the commands have AutocompleteVisible turned on **by default**. This means that Adonis is not checking whether a user should be seeing these commands in the chat autocomplete.

This issue appears to have been existent since around November of 2023, when support for TextChatCommands in Adonis was added.

### Device

Windows

### Relevant log output

_No response_

### LINKED ISSUE #1607: The "Poison" command only works once.
### Version channel

Nightly

### Loader version

_No response_

### What part of Adonis is this related to?

Command

### What happened?

https://github.com/user-attachments/assets/49ce6dbe-e698-499e-83ce-65add6bbb5bc

Using the poison command on myself, it only works once and when I want to use it again it just doesn't work (it only works after a reset).
Maybe I'm wrong but maybe it should kill the player until the end

### Device

Windows

### Relevant log output

_No response_

### LINKED ISSUE #1608: Set ResetOnSpawn to false in Dex
### What part of Adonis is this related to?

Command

### What are you suggesting?

It's frustrating that every time I die in the game I have to rerun the dex command

### LINKED ISSUE #1664: Adonis causes warning: "RunContext of LocalScript is fixed to Legacy", "New value will be ignored"
### Version channel

Stable (Default)

### Loader version

260

### What part of Adonis is this related to?

Other

### What happened?

On games which use Adonis, a recent update (I don't know when) caused it to start outputting the following warning:

`The RunContext of LocalScript is fixed to Legacy and cannot be changed. New value will be ignored.`

image

This happens, in the shown order, every time you run the game whether in the player or studio.

### Steps to reproduce

Run a game with Adonis.

### Device

Windows

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ccuser44**
Fixes:
- Fix broken atmosphere handling
- Fix atmosphere for client
- Fix TextChat command suggestions not respecting permission level - Fixes #1600
- Fix poison command only working once - Fixes #1607
- Fix private info not showing for self in `!profile` - Fixes #1578
- Fix Dex disappearing after respawn - Fixes #1608
- Fix Dex sometimes not fetching newest APIs and Dex plugin delaying Adonis boot
- Fix friends page old online API not working anymore - Fixes https://devforum.roblox.com/t/updating-friends-api-deprecating-isonline-property-from-getfriendsasync/3171177
- Fix `!fps` updating infrequently - Fixes #1555
- Fix other misc bug fixes and optimizations with audioplayer and overhaul some parts of it. Commit for easier reviewing due to file replacement: https://github.com/Epix-Incorporated/Adonis/commit/e37abf91a372b4e24d0d6a8be7f45dba79bc8352
	- Fix audio player not skipping to next track - Fixes #1574
	- Fix audio player forward and backwards buttons not working
	- Fix audio player position slider being broken
	- Fix audio player Adonis audio adding game audios
	- Fix audio player volume controls being way too sensitive
	- Fix misc bugs in audioplayer and optimize it
- Fix `:zawarudo` audios being broken - Fixes: [Zawarudo has 2 broken audios](https://discord.com/channels/81902207070380032/1238053069367939133/1238053069367939133)
- Fix `:clearguis` not removing Dex
- Fix some themes Hints and Notifs not respecting `TopBarShift` and having a weird position
- Fix console not respecting TopBar size
- Fix `:showlogs` not working. Someone changed the argument order a few years ago, this changes it back. - Fixes: [showlogs command doesn't work](https://discord.com/channels/81902207070380032/1214141268045729842/1214141268045729842)
- Fix notification icon missing for Aero theme
- Fix notification icon missing for Windows XP theme
- Fix `:sing` not working sometimes in game and fix some rojo and model issues. - Fixes #1664 Fixes: [Fix sing command](https://discord.com/channels/81902207070380032/1209965618229674034/1209965618229674034)
- Fix `:backupmap` not backup up gravity or lighting
- Fix invalid/weird brush position for `!paint`
- Fix Unity theme `functionify` lint error
- Fix nightlymode not being used in nightly branch builds
- Fix backup loader not working
- Fix `!serverdetails` showing incorrect physics FPS
- Fix `!serverdetails` not working in studio
- Fix non-player aliases not working
- Fix not all outputs respecting `Settings.SilentStartup`
- Fix render resolution showing decimals for pixel amount in `!profile`
- Fix `service.GetProductInfo` being broken due to invalid cache timestamp
- Fix invalid string pattern for numbered player selector
- Fix `:starterscripts` invalid `table.insert` arguments
- Fix `:giveppoints` not sending a notification. Roblox has fully bricked the API now.
- Misc fixes

Changes:
- Add `:UnZaWarudo`
- Make `!paint` use `EditableImage`s. This adds a speed boost for large amounts of pixels
- Allow users to upload their own creations in `!paint` as Roblox decals
- Redo `AudioLib.luau` from the ground up to make it work
- Change Music Player dependencies `Signal` to Adonis GoodSignal and `Slider` to newest version. Fixes some breaking bugs
- Add loading animation to indicate audios loading in music player
- Add a much better version system
- Make unknown user logs a lot more user friendly.
- Convert many things to use `Settings.Message`s
- Move `:testfilter` to the debug plugin
- `:debugtesterror` from `Creators` to `Players`
- `:debugtestbiglist` from `Creators` to `Admins`
- `:debuganti` from `Creators` to `Head Admins`
- Optimise `:jail` color arg parsing
- Optimise `Functions.ArgsToString`
- Optimise `Admin.FormatCommandArguments`, `Admin.FormatCommand` and `Admin.FormatCommandAdminLevel`, improves Adonis speed considerably
- Optimise `service.FormatNumber`
- Optimise `UserPanel.luau` tab to string
- Convert `AudioPlayer.rbxmx` to raw files instead of XML
- Convert `:size` to use a variable for default max size

Removed:
- Remove `service.GetUserType`. It's a useless pre-FilteringEnabled relic
- Remove `client.TestEvent`. It's useless
- Remove `ChatCreateRobloxCommands` from `Settings` as it's no longer needed due to the bug being fixed.
- Remove `service.OwnsAsset`, just an unused alias for `service.CheckAssetOwnership`
- Remove usage of `Anti.ClassName` from `UI.lua`. It's a deprecated and nonexistent pre-FilteringEnabled relic
- Remove `service.IsLocked`, another pre-FilteringEnabled relic
- Remove `:flatten` unused `CharacterMesh` check
- Remove unused `doPcall`
- Remove unused `enumMats` in `:material`
- Remove `Functions.CatchError`. Totally useless and dublicated by `Pcall`
- Delete `Topbar.rbxmx` from `Unity`
- Delete severely out of date Audio Player copy from `Unity`
- Remove legacy references of TopBars
- Misc bloat&cruft

Minor misc changes:
- Fix streaming enabled and archivable for `:jail`
- Fix streaming enabled and archivable for `:clone`/`:loadavatar`
- Fix streaming enabled and archivable for `:ufo`
- Fix streaming enabled for `:bot`
- Fix streaming enabled for `:nuke`
- Fix `:pipe` archivable
- Fix AudioLib archivable
- Fix `:sfling` archivable
- Fix `:clown` archivable
- Fix TextChatCommands archivable
- Fix `:tornado` name
- Fix `:chik3n` parent
- Convert some `math.random()` to use `HttpService:GenerateGUID()`

> I said let him cook

### CODE REVIEW

**Comment by ccuser44** [comment]
@Expertcoderz @Dimenpsyonal @P3tray PoF is here, this can be merged.

PoF:
image
image

Van&UFO PoF:
image
image

AudioPlayer PoF:
image

DeX PoF:
image

Nuke PoF:
image

Aliases PoF:
image
image

**Comment by P3tray** [comment]
can you please unhandle the decimals? i prefer mine free-range.

**Comment by ccuser44** [comment]
> can you please unhandle the decimals? i prefer mine free-range.

No, you cant have half pixels + the decimals bug happens 2 often.

**Comment by P3tray** [comment]
This PR is hidden malware roulette. There's no way i'm reading all of that.

**Review by P3tray — APPROVED** [review]
Didn't check.

**Comment by P3tray** [comment]
> Kill yourself ccuser44

what fixing the atmosphere variables and perfstats does to the community

**Comment by ccuser44** [comment]
@Dimenpsyonal Do I break this up to multiple pulls to make it easier to merge and review?

**Comment by ccuser44** [comment]
Fixed conflict with master.

**Comment by ccuser44** [comment]
Fixed conflict

**Pull request merged**
