### PR TITLE
Added New Dex Plugin

### PR DESCRIPTION
**Pull request by karl-police**
Adds the New Dex as a Server Dex similar to the current one. This doesn't replace the current Dex, it just adds a new command.

The repository to the New Dex can be found here https://github.com/LorekeeperZinnia/Dex created by @LorekeeperZinnia.

There's some stuff missing, but especially Calling Remotes. The original repository is unfinished, but the basic functionality is there and the UI is very nice.

I don't know how to invite @LorekeeperZinnia as a contributor to this pull request, someone please do.

Adds this command.
```lua
Commands.DexExplorerNew = {
		Prefix = Settings.Prefix;
		Commands = {"dexNew";"dexNewExplorer";};
		Args = {};
		Description = "Lets you explore the game using new Dex [Credits to LorekeeperZinnia]";
		AdminLevel = 300;
		Function = function(plr, args)
			ServerNewDex.Authorized[plr] = {
				Clipboard = {};
			}; --// double as per-player explorer-related data

			if not ServerNewDex.Event then  ServerNewDex.MakeEvent(); end
			Remote.MakeLocal(plr, newDex_main:Clone(), "PlayerGui")
		end
	};
```

Another thing that I did, was to make the UI a bit more transparent instead of no transparency at all, to be as nice as the current Server Dex.

image

image

### CODE REVIEW

**Comment by karl-police** [comment]
Also, since I put this New Dex here and some people are gonna find it probably. Don't create derivation of it for whatever, without crediting who originally created the New Dex Explorer in the first place.

If you look at all the existing Dex explorers and how bad some people modified them, it's horrible.

**Review by LiveFireExercise — APPROVED** [review]
Yes

**Comment by karl-police** [comment]
@Sceleratis is it possible to give pull request permissions to update this?

**Comment by LiveFireExercise** [comment]
no

**Comment by watameln** [comment]
cat

**Pull request merged**
