### PR TITLE
Fix for "Unity" theme. Window Gui is creating unnecessary instances

### PR DESCRIPTION
**Pull request by EgizianoEG**
**Bug:**
  - There was multiple, many, and unnecessary instances (UICorner) being created by the script due to not implementing an "if" statement before the creation of a new one...

**Demonstration:** 
 - notes marker

**Solution:**
  - Simple "if not" statement to determine if the tooltip is in need for a new UICorner or not.

### CODE REVIEW

**Comment by P3tray** [comment]
@LolloDev5123's monkey code at work

**Review by P3tray — APPROVED** [review]
image

**Comment by LolloDev5123** [comment]
> @LolloDev5123's monkey code at work

Hey at least it works

**Review by ccuser44 — APPROVED** [review]

**Comment by LolloDev5123** [comment]
It's a very beautiful theme isn't it

**Review by LolloDev5123 — COMMENTED** [review]
so, pawn?

**Comment by LiveFireExercise** [comment]
if only it’s creator would update it 🙄🙄

**Review by Expertcoderz — APPROVED** [review]

**Pull request merged**
