### PR TITLE
Fix the weird readme links

### PR DESCRIPTION
**Pull request by LiveFireExercise**
Pretty sure expertcoderz added these and then it turned out they didn't work soooo

### CODE REVIEW

**Comment by Expertcoderz** [comment]
No, I did not add those.

**Comment by LiveFireExercise** [comment]
I don't believe you.

**Comment by moo1210** [comment]
Epix-Incorporated/Adonis@0c26c20 https://github.com/Epix-Incorporated/Adonis/pull/1024. Rats.

**Comment by LiveFireExercise** [comment]
Fine... You win this time Expertcoderz...

**Comment by moo1210** [comment]
I found out that the above-mentioned PR caused many more issues, which I will be resolving in my big PR shortly.

**Pull request merged**
