### PR TITLE
Merge master into release branch

### PR DESCRIPTION
**Pull request by Dimenpsyonal**

### CODE REVIEW

**Comment by Dimenpsyonal** [comment]
wHY won't this work

**Comment by WalkerOfBacon** [comment]
lint failed xd

**Comment by Dimenpsyonal** [comment]
shut

**Comment by WalkerOfBacon** [comment]
I did not read

**Comment by WalkerOfBacon** [comment]
> shut

no

**Comment by Dimenpsyonal** [comment]
Screenshot 2023-11-05 at 16 07 59

why is the release branch like this

**Comment by Dimenpsyonal** [comment]
and i cant even resolve the conflicts because my github desktop window wont open

**Comment by Dimenpsyonal** [comment]
my github desktop keeps crashing. ugghhhhh

**Comment by moo1210** [comment]
Adonis v240 has been canceled because this GitHub repo stinks. Sorry for the inconvenience,

**Comment by Dimenpsyonal** [comment]
If only I could delete and it smh

**Comment by Dimenpsyonal** [comment]
I DIT IT!!! IM THE BEST CODER TO EVER EXIST

**Pull request merged**
