### PR TITLE
string lib functions optimization

### PR DESCRIPTION
**Pull request by ocelot81**
some minor changes to account for Luau's performance magic 🐈‍⬛
hopefully no env malware in service.lua

### CODE REVIEW

**Review by ccuser44 — APPROVED** [review]
Although this wont optimise because Adonis uses getfenv

**Comment by Dimenpsyonal** [comment]
> Although this wont optimise because Adonis uses getfenv

How does getfenv unoptimise it

**Comment by Dimenpsyonal** [comment]
also pls fix
image

**Comment by ccuser44** [comment]
> > Although this wont optimise because Adonis uses getfenv
> 
> How does getfenv unoptimise it

If getfenv is in code a lot of Luau optimisations depending on globals wont work because the safeenv flag is flipped off

**Comment by Dimenpsyonal** [comment]
But why

**Comment by ccuser44** [comment]
> But why

It's just not

**Comment by Dimenpsyonal** [comment]
Simply disable getfenv

**Comment by ocelot81** [comment]
> also pls fix image

NOOO

**Comment by Dimenpsyonal** [comment]
u forgot the closing bracket.....

**Comment by ocelot81** [comment]
ok fixed 1 secon!

**Comment by Dimenpsyonal** [comment]
not fixed. u added it in the wrong place smh

**Comment by ocelot81** [comment]
how...

**Comment by ccuser44** [comment]
> how...

^{service.SanitizePattern(string.lower(s)**)**}`)
not
^{service.SanitizePattern(string.lower(s)}`)**)**

**Comment by Dimenpsyonal** [comment]
Exactly. Ur closing off the string before the string.lower has been closed

**Comment by ocelot81** [comment]
god i hate the github.

**Comment by Dimenpsyonal** [comment]
Bro you edited the wrong line

**Comment by ocelot81** [comment]
fucking hell

**Comment by PurpleCreativity** [comment]
Shut up @ocelot81 Skid

**Comment by ocelot81** [comment]
BEAR WITH ME I NEVER GITHUBBED

**Comment by PurpleCreativity** [comment]
ocelot81:luau-builtins-optimization

**Comment by SuperCater** [comment]
Adonis is going to explode the moment you merge this.

**Comment by PurpleCreativity** [comment]
Adonis is going to explode the moment you merge this.

**Comment by EasternBloxxer** [comment]
Adonis is going to explode the moment you merge this..

**Comment by Dimenpsyonal** [comment]
Adonis is going to explode whether or not I merge this

**Comment by PurpleCreativity** [comment]
Follow your merging rules that you've been ignoring for the past 2 years

**Comment by SuperCater** [comment]
While we're on the topic we really should consider looking into removing all the env tampering madness fully.

It disables luau performance enhancements and in general is just considered bad practice now.

**Comment by PurpleCreativity** [comment]
Shut up.

**Comment by ccuser44** [comment]
> While we're on the topic we really should consider looking into removing all the env tampering madness fully.
> 
> It disables luau performance enhancements and in general is just considered bad practice now.

There is some usage to setting global env variables though in the Admin modules so we'd need an alternative way

**Comment by Dimenpsyonal** [comment]
> Follow your merging rules that you've been ignoring for the past 2 years

a. I only became maintainer in sept 2023 so not 2 years
b. Theres no mergeing rules buddy
c. POLSKA

**Comment by ocelot81** [comment]
good luck untangling all the setfenvs from 2016 code inshallah

**Comment by PurpleCreativity** [comment]
your third point is invalid

**Comment by PurpleCreativity** [comment]
😿😿

**Comment by Dimenpsyonal** [comment]
> your third point is invalid

image

**Comment by PurpleCreativity** [comment]
you will step on a lego tonight

**Comment by SuperCater** [comment]
I forgot how but i managed to remove it fully from my like V239 fork on both the server, client, and service modules.

It was a pain but i believe its possible without reducing functionality it seems.

**Comment by ocelot81** [comment]
FR

**Comment by Dimenpsyonal** [comment]
> I forgot how but i managed to remove it fully from my like V239 fork on both the server, client, and service modules.

Amazing. If only this could be for base adonis

**Comment by PurpleCreativity** [comment]
🍴

**Comment by ccuser44** [comment]
> I forgot how but i managed to remove it fully from my like V239 fork on both the server, client, and service modules.
> 
> It was a pain but i believe its possible without reducing functionality it seems.

We'd have to manually set the globals then

**Comment by ocelot81** [comment]
whats the point of globals then

**Comment by ocelot81** [comment]
iirc adonis sets logerror, getenv etc as globals but you can just manually set them with server.logError

**Comment by Dimenpsyonal** [comment]
i say we start doing this immediately

**Comment by ocelot81** [comment]
so true

**Comment by PurpleCreativity** [comment]
Teamwork makes the Dream work!

**Comment by ccuser44** [comment]
But, remember to set globals before you set locals

**Comment by PurpleCreativity** [comment]
@Dimenpsyonal @SuperCater you guys go first!

**Comment by SuperCater** [comment]
I would work on it if not for the fact anytime i load adonis in vscode is 9 million warnings

**Comment by ccuser44** [comment]
getenv should be renamed to getaenv

**Comment by ocelot81** [comment]
expertcoderz will be heartbroken when env hacks will be deleted

**Comment by Dimenpsyonal** [comment]
> I would work on it if not for the fact anytime i load adonis in vscode i get 9 million warnings

more reason to convert it!! simply do what I do and write it in roblox studio

**Comment by SuperCater** [comment]
Sadly there is a major downside if we do this, it will break all existing plugins that rely on the env, and all custom themes with UI modules that rely on the env.

**Comment by ocelot81** [comment]
only theme we need is rounded. i see this as an absolute win

**Comment by Dimenpsyonal** [comment]
> Sadly there is a major downside if we do this, it will break all existing plugins that rely on the env, and all custom themes with UI modules that rely on the env.

Ok so we simply tell people in advance. Ez

**Comment by ccuser44** [comment]
server and service still should be manually set as globals

Also adonis relies on a few global replacements for assert and legacy wait functions

**Comment by Dimenpsyonal** [comment]
why

**Comment by ocelot81** [comment]
OH

**Comment by ocelot81** [comment]
OMFG

**Comment by PurpleCreativity** [comment]
dumb

**Comment by SuperCater** [comment]
Thankfully the pull request exploded, not Adonis

**Pull request closed without merging**
