### PR TITLE
Removed CustomChat 

### PR DESCRIPTION
**Pull request by EasternBloxxer**
This chat was deprecated a long time ago and hasn't received any updates since. 
The chat has a lot of issues and currently seems to be used only to break Roblox TOS by giving console players a chat.

### CODE REVIEW

**Comment by coasterteam** [comment]
A lot of people won't like this but it must be done

**Comment by Dimenpsyonal** [comment]
yea tbh. too much of a hassle

**Comment by EasternBloxxer** [comment]
There. Fixed.

**Comment by EasternBloxxer** [comment]
image
This is still  that but it should be back to original

**Pull request merged**
