### PR TITLE
Fix odd issue

### PR DESCRIPTION
**Pull request by ccuser44**
~~This only appears sometimes (why?) (a sign of a deeper issue in Adonis that needs investigation)~~

### CODE REVIEW

**Comment by WalkerOfBacon** [comment]
THANK YOU

**Comment by ccuser44** [comment]
I found the deeper issue in Adonis. Crossserver bricks Adonis

**Comment by WalkerOfBacon** [comment]
oh wow

**Comment by WalkerOfBacon** [comment]
definitely needs to be checked

**Review by WalkerOfBacon — APPROVED** [review]

**Comment by ccuser44** [comment]
#1284 fixes the deeper issue

**Pull request merged**
