### PR TITLE
Fix Typo in Changelog

### PR DESCRIPTION
**Pull request by ScriptedConnor**
Found a typo in the change log. Decided to fix it.

### CODE REVIEW

**Comment by WalkerOfBacon** [comment]
ironic that the typo you fixed was about fixing a typo

**Comment by ScriptedConnor** [comment]
for real

**Comment by Dimenpsyonal** [comment]
> ironic that the typo you fixed was about fixing a typo

thats not a coincidence. thats intentional bruh

**Comment by Sqikerz** [comment]
Yeah I was going to say I'm pretty sure it's intentional 😭

**Comment by P3tray** [comment]
> Found a typo in the change log. Decided to fix it.

The typeo was intentional.

**Pull request closed without merging**
