### PR TITLE
Serverlock server on softshutdown

### PR DESCRIPTION
**Pull request by ccuser44**
Prevents infinite loops.

### CODE REVIEW

**Comment by Dimenpsyonal** [comment]
Do admins bypass serverlock? If so, and if there are multiple admins, could this not split them up

**Comment by ccuser44** [comment]
> Do admins bypass serverlock? If so, and if there are multiple admins, could this not split them up

Yes, but you could make the case the admins would need to join there for maintenance or something?

**Comment by ccuser44** [comment]
I dont think this needs the PoF
The code is the same as serverlock

**Comment by Dimenpsyonal** [comment]
Yea I'd just like to see it so that I can make certain it works

**Comment by ccuser44** [comment]
> Yea I'd just like to see it so that I can make certain it works

Just check the code of serverlock it flips the same flag so there is no difference

**Comment by Dimenpsyonal** [comment]
Yea I know the code is fine but I just need a video of it working

**Comment by DrewBokman** [comment]
wouldnt this make it so players would get kicked during a restart? doesnt that kinda defeat the point

**Comment by ccuser44** [comment]
> wouldnt this make it so players would get kicked during a restart? doesnt that kinda defeat the point

no

**Comment by Sqikerz** [comment]
The infinite loop is still caused. I believe this only happens when 2+ players are in-game:

https://youtu.be/-2gti6tgn_A

**Comment by Dimenpsyonal** [comment]
exactly

**Comment by simulified** [comment]
There is a problem
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 1000; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by EasternBloxxer** [comment]
> The infinite loop is still caused. I believe this only happens when 2+ players are in-game:
> 
> https://youtu.be/-2gti6tgn_A

just kick the player right after the teleport 
I do this in astra and i have had no issues

**Pull request closed without merging**
