### PR TITLE
Use JIT compiler optimization for Linked List, GoodSignal and Type Checker modules

### PR DESCRIPTION
**Pull request by ccuser44**
Use JIT compiler optimization for Linked List, GoodSignal and Type Checker modules

### CODE REVIEW

**Comment by ccuser44** [comment]
@Dimenpsyonal Done.

**Comment by Dimenpsyonal** [comment]
i dont get what this does

**Comment by ccuser44** [comment]
> i dont get what this does

Uses JIT compiler optimization for Linked List, GoodSignal and Type Checker.

**Comment by Dimenpsyonal** [comment]
idk what that is

**Comment by ccuser44** [comment]
https://en.wikipedia.org/wiki/Just-in-time_compilation

**Comment by Dimenpsyonal** [comment]
Ok but does this do anything on boblox

**Comment by ccuser44** [comment]
> Ok but does this do anything on boblox

Yes. The FiOne script is JITd too.

I got the idea to do this for other modules from https://github.com/Astra-Corporation/Astra.Admin but didn't decide to use the optimize 2 directive and only the JIT directive for debugging reasons

**Pull request merged**
