### PR TITLE
Make disabling linkedlists a loader flag

### PR DESCRIPTION
**Pull request by ccuser44**
^^

It's problematic to only have a setting in defaultsettings.
Better change it to a loader flag.

### CODE REVIEW

**Comment by Dimenpsyonal** [comment]
You already tried this and it broke Adonis

**Comment by ccuser44** [comment]
> You already tried this and it broke Adonis

This doesn't break Adonis
The other one happened because variables didnt exist
The flag here is set on the bootstrapper call before anything else even happens

**Comment by Dimenpsyonal** [comment]
why do you hate LinkedLists being in settings!!!

**Comment by kaiserandaxl** [comment]
Linked list should always be used

**Comment by ccuser44** [comment]
> Linked list should always be used

@Dimenpsyonal and @coasterteam said there should be a toggle

**Comment by Dimenpsyonal** [comment]
> @Dimenpsyonal and @coasterteam said there should be a toggle

@ccuser44 yea and there is. it's in defaultsettings

**Comment by ccuser44** [comment]
image


> > @Dimenpsyonal and @coasterteam said there should be a toggle
> 
> @ccuser44 yea and there is. it's in defaultsettings

And it should be made a loader flag

**Comment by ccuser44** [comment]
Proof of functionality:
image
image
image
image
image
image
image
image

**Pull request merged**
