### PR TITLE
Updated ServerNewDex Plugin, with new features

### PR DESCRIPTION
**Pull request by karl-police**
Once I added this https://github.com/Epix-Incorporated/Adonis/pull/1019

This is an update for the New Dex Plugin.

Originally, New Dex is unfinished.

These buttons are now functional.

image

The Settings and Information button, have now all functions.

Some of the settings in New Dex are not even used, so I'm not even displaying them. The settings do not save, maybe I will add something for it eventually, along with an option to reset them all. For now it's just the settings editor, not an entire re-structure of how Settings are implemented in New Dex.

image

image

Not only that, but as you may see I've actually added a few more settings other than that.

``ClickToSelect``, it will select the thing you're clicking and aiming at.

You can edit the theme in the settings, however it won't refresh anything. Theme changing isn't fully done yet. Maybe in the future I will do something.

The LocalScript now gets put inside a ScreenGui called "Dex_Client" so that you can toggle "ResetOnSpawn" off manually through Dex. _(Not through Roblox Studio Client window, as the server gives the client the ScreenGui, where the Server has it set on "true")_

I've also renamed the version.

In Addition, I have updated the API Dump and the RMD. Which is a nice timing, since Roblox recently added AirController or sometihng.

What GuiToLuaAE is, it's a Plugin that basically just generates serialized instance code from a ScreenGui, just that the one I used was modified, so it's more personalized for Dex's code style

### CODE REVIEW

**Comment by karl-police** [comment]
@Sceleratis :)

**Comment by Dimenpsyonal** [comment]
Didn't dex like... Update

**Comment by karl-police** [comment]
> Didn't dex like... Update

there's two, the old version and this is the new version

**Comment by Dimenpsyonal** [comment]
Is this sourced from somewhere or did you update it

**Comment by cocooo23** [comment]
He sourced the newest official Dex release but with his own additions (like settings) because this version of Dex never finished

**Comment by Dimenpsyonal** [comment]
I see

**Comment by ccuser44** [comment]
Did you add credits to `Credits.lua`?

**Comment by Dimenpsyonal** [comment]
How do you access this though; all this PR does is add the file

**Comment by ccuser44** [comment]
> How do you access this though; all this PR does is add the file

I think it is `:dewnew`

**Comment by Dimenpsyonal** [comment]
Ohh... Ok

**Comment by karl-police** [comment]
> Did you add credits to `Credits.lua`?

the original dev didn't even want to be attached as contributor on this GitHub request
I wouldn't say that the current credits about old Dex are accurate either.

**Pull request merged**
