### PR TITLE
Made cape parented to character and massless

### PR DESCRIPTION
**Pull request by DaEnder**
Fixed some issues with capes on R15 and made it Massless.

https://user-images.githubusercontent.com/54174182/177046556-cddea334-e160-4991-a7ad-6b58a010323c.mp4

### CODE REVIEW

**Comment by DaEnder** [comment]
Forgot CanQuery to false and idk how to fix it so yes

**Comment by GalacticInspired** [comment]
doesn't this break the disable capes setting in the client?

**Comment by DaEnder** [comment]
well does it?

**Comment by DaEnder** [comment]
might have issues; needs testing
image
(idk if its related)

**Comment by ccuser44** [comment]
The `.Massles` and the `.CanQuery` additions make sense, but I don't see why it should be parented to the character, it could cause potential issues too.

**Comment by DaEnder** [comment]
so its hidden when in first person it can be annoying at times

**Comment by DaEnder** [comment]
btw some stuff broke with this trying to figure out atm

**Comment by Gatorzgaming** [comment]
> The `.Massles` and the `.CanQuery` additions make sense, but I don't see why it should be parented to the character, it could cause potential issues too.

This issue could be mediated with a setting for it but I imagine adding a new setting is hard to do, due to older clients

**Comment by h0nzzz** [comment]
it being parented to the character makes it so you cant see it in first-person

**Comment by P3tray** [comment]
> so its hidden when in first person it can be annoying at times

### HELLO!

You can write custom code into the client to handle cape hiding in first person. Stop relying on Roblox core to do your lazy ass dirty work.

This custom code can also be used to hide capes on the client with the hide capes setting, if you so cared. Alternatively use real `Instance.Transparency` like a non-degenerate would.

**Comment by Gatorzgaming** [comment]
@DaEnder  Did you forget about this lol?

**Comment by DaEnder** [comment]
no im lazy

**Comment by DimensionalFusion** [comment]
@Expertcoderz Merge when.

**Comment by Expertcoderz** [comment]
> @Expertcoderz Merge when.

I'll do a bit of testing and get it merged by the next 24 hours from now.

**Comment by DimensionalFusion** [comment]
Ok

**Pull request merged**
