### PR TITLE
Remove legacy PointsService command

### PR DESCRIPTION
**Pull request by ccuser44**
Removes legacy givepoints command [PointsService has been disabled totally](https://devforum.roblox.com/t/retiring-pointsservice/2318767)

### CODE REVIEW

**Comment by Dimenpsyonal** [comment]
No

**Comment by FungusGenerator** [comment]
literally 1984

**Comment by Dimenpsyonal** [comment]
Haha. Merge conflict.

**Comment by ccuser44** [comment]
Superseded by #1334

**Pull request closed without merging**
