### PR TITLE
Add BTools option to bug reports

### PR DESCRIPTION
**Pull request by ccuser44**
Add BTools option to bug reports

### CODE REVIEW

**Comment by Dimenpsyonal** [comment]
Why tho

**Comment by ccuser44** [comment]
Many btools issues

**Comment by joritochip** [comment]
Issues with F3X should be brought to the team that maintains F3X, not us

**Comment by ccuser44** [comment]
> Issues with F3X should be brought to the team that maintains F3X, not us

And this makes identifying that more quick

**Comment by ccuser44** [comment]
And with this we can even have a bot that automatically closes the issue and tells the people to go to the F3X repository

**Comment by Dimenpsyonal** [comment]
I dont think that's necessary

**Comment by ccuser44** [comment]
> I dont think that's necessary

I dont see any downsides

**Comment by Dimenpsyonal** [comment]
Can't a maintainer can close any issues that have to do with btools

**Comment by ccuser44** [comment]
> Can't a maintainer can close any issues that have to do with btools

Having an autoclose would be a lot better
Less work less humiliation rituals

**Comment by Dimenpsyonal** [comment]
Maybe so but this PR doesn't have an autoclose

**Comment by ccuser44** [comment]
:(

**Comment by Dimenpsyonal** [comment]
Sad ikr

**Pull request closed without merging**
