### PR TITLE
Convert .lua files to use .luau

### PR DESCRIPTION
**Pull request by Dimenpsyonal**
Was there a better way? Probably.
Did I bother to research? No.
Did I do it anyway? Yes.

### CODE REVIEW

**Comment by ccuser44** [comment]
This is bad

**Comment by Dimenpsyonal** [comment]
> This is bad

and why do you think that

**Comment by moo1210** [comment]
Maybe if anyone opened the ___ project within the last week they'd know

**Comment by Dimenpsyonal** [comment]
what??

**Pull request merged**
