### PR TITLE
Fix console cursor being very hard to see

### PR DESCRIPTION
**Pull request by EasternBloxxer**
A Roblox change made the console cursor black but this pr should hopefully fix it

### CODE REVIEW

**Comment by h0nzzz** [comment]
roblox updates are fun

**Comment by EasternBloxxer** [comment]
Very

**Review by Expertcoderz — APPROVED** [review]

**Comment by Sceieratis** [comment]
This Pull Request Broke Adonis! I have reverted it. Thanks!

**Comment by EasternBloxxer** [comment]
Did it fr?  i tested it and it worked. Will look into it later

**Comment by EasternBloxxer** [comment]
> This Pull Request Broke Adonis! I have reverted it. Thanks!

🤓

**Pull request merged**
