### PR TITLE
Create `:sing` command

### PR DESCRIPTION
**Pull request by ccuser44**
This can also be used as a portable sound source

### CODE REVIEW

**Comment by Dimenpsyonal** [comment]
What does this do again

**Comment by cocooo23** [comment]
lalalaalalalaala

**Comment by Dimenpsyonal** [comment]
Tra la la laaaa!

**Comment by Dimenpsyonal** [comment]
image

@ccuser44 Why is the meta not right!!!

**Comment by ccuser44** [comment]
> 
> @ccuser44 Why is the meta not right!!!

Rojo has not been updated

**Comment by ccuser44** [comment]
> > 
> > @ccuser44 Why is the meta not right!!!
> 
> Rojo has not been updated

Nvm it was because it was a modulescript instead of a server script
Fixed in #1247

**Pull request merged**
