### PR TITLE
Generic commit title.

### PR DESCRIPTION
**Pull request by P3tray**
## Notice
* Make sure you have read https://github.com/Epix-Incorporated/Adonis/blob/master/CONTRIBUTING.md before contributing!
* Ensure you title your PR correctly and that you include your proof of functionality as well as a description of what you have done, and a rationale as to why.
* **Remember to delete this section when you submit your PR!**

i cant read

### CODE REVIEW

**Comment by WalkerOfBacon** [comment]
Remember to delete this section when you submit your PR!

**Comment by Dimenpsyonal** [comment]
1. u didn't update defaultsettings 
2. u didn't change settings.Order
smh noob.

**Comment by kaiserandaxl** [comment]
Why we moving DefaultTheme?

**Comment by P3tray** [comment]
> 1. u didn't update defaultsettings
> 2. u didn't change settings.Order
>    smh noob.

1. dont need to BOZO
2. fair enough

**Comment by P3tray** [comment]
> Why we moving DefaultTheme?

too many kids keep changing it without reading what it does and wondering why their shit is borked

**Review by P3tray — COMMENTED** [review]
@Dimenpsyonal done

**Comment by P3tray** [comment]
woohoo

**Pull request merged**
