### PR TITLE
Fix to PR #1155

### PR DESCRIPTION
**Pull request by WalkerOfBacon**
aaaaaaaaa
https://github.com/Epix-Incorporated/Adonis/pull/1155

### CODE REVIEW

**Comment by karl-police** [comment]
> aaaaaaaaa #1155

I'd just revert the entire thing back to normal.

**Comment by WalkerOfBacon** [comment]
> > aaaaaaaaa #1155
> 
> I'd just revert the entire thing back to normal.

Agreed

**Comment by karl-police** [comment]
> > > aaaaaaaaa #1155
> > 
> > 
> > I'd just revert the entire thing back to normal.
> 
> Agreed

I even wrote entire "essay", to justify on why. 😭

**Comment by karl-police** [comment]
also the Prefix = Prefix thing would still be nil

it's pointless

**Comment by WalkerOfBacon** [comment]
> also the Prefix = Prefix thing would still be nil
> 
> it's pointless

I guess

**Pull request closed without merging**
