### PR TITLE
Add backwards compatibility code to a dedicated plugin

### PR DESCRIPTION
**Pull request by ccuser44**

### CODE REVIEW

**Comment by Dimenpsyonal** [comment]
Does this redirect functions automatically

**Comment by ccuser44** [comment]
> Does this redirect functions automatically

The behavior is the same as before. I think yes.

**Comment by Dimenpsyonal** [comment]
Idk I can't merge based on "I think"

**Comment by ccuser44** [comment]
Yes it is. it does the same thing expect from a plugin

**Pull request merged**
