### PR TITLE
Remove blatant racism.

### PR DESCRIPTION
**Pull request by IndependentBlackWoman**
Hello Epix Incorperated.

I am a strong Independent Black Woman. I am not okay with your admin system having blatant racism. There is NO such evidence of black people having KFC powers, such assumptions are based on race and no actual evidence. My daughter was CRYING because she wanted to make a ROBLOX game and when she chose to use Adonis, there was RACISM. This is not okay. But I assumed there is hope because I saw that [in a commit you removed calling Child Pornography.](https://github.com/Epix-Incorporated/Adonis/commit/ac3f910ebdefb604b5467565136a4145e166a3aa) Please remove this racism from your code.

Thank you,
Sasha Grey

### CODE REVIEW

**Comment by WalkerOfBacon** [comment]
what?!?!?!?!

**Comment by dalloc2** [comment]
╔══════════════ ೋღ☃ღೋ ══════════════╗
If you are a beautiful strong black woman, someone will put this in your comments.
╚══════════════ ೋღ☃ღೋ ══════════════╝

**Comment by simulified** [comment]
Looks good to me

**Comment by ocelot81** [comment]
Remove RACISM immediately

**Comment by estraco** [comment]
holy moly

**Comment by SomePogProgrammer** [comment]
ain't no way there's a pull request for "removed blatant racism" 👁️

**Comment by SuperCater** [comment]
We need to add settings.RacismCommands

**Comment by bigbenster702** [comment]
That's crazy

**Comment by 7n7o** [comment]
╔══════════════ ೋღ☃ღೋ ══════════════╗
If you are a beautiful strong black woman, someone will put this in your comments.
╚══════════════ ೋღ☃ღೋ ══════════════╝

**Review by watameln — APPROVED** [review]
I approve of this pull request

**Review by P3tray — CHANGES_REQUESTED** [review]
Command is a reference to ZeLIth and Prologue:

https://www.roblox.com/users/916133447/profile
https://www.roblox.com/games/3780695282/Prologue

Also see:
https://mythcommunity.fandom.com/wiki/Robloxian_Myth_Hunters
https://mythcommunity.fandom.com/wiki/ZeLIth

**Comment by LolloDev5123** [comment]
I rightfully believe we should add more racist commands, thanks for the ideas.

**Comment by P3tray** [comment]
> I rightfully believe we should add more racist commands, thanks for the ideas.

image

**Pull request closed without merging**
