### PR TITLE
Tabelise settings

### PR DESCRIPTION
**Pull request by LiveFireExercise**
silly i know

### CODE REVIEW

**Comment by LiveFireExercise** [comment]
i know right. im so cool.

**Comment by LiveFireExercise** [comment]
no i remembered it. but then i remembered i didnt care

**Comment by NoobBucket** [comment]
🤡

**Comment by LiveFireExercise** [comment]
> you = 🤡

is what you said to yourself in the mirror

**Comment by NoobBucket** [comment]
yeah the mirror with no mirrorness about it with you behind it

**Comment by LiveFireExercise** [comment]
you said as you remembered you didn't take your schizophrenia pills, and the person you were seeing was yourself

**Comment by NoobBucket** [comment]
but if it meant i thought it was you, the point still stands 😎

**Comment by LiveFireExercise** [comment]
it does not as my actions were imaginary, and by extension they were your imagination which is pulled from your consciousness, which means it is you

**Comment by NoobBucket** [comment]
but my consciousness considered it to be you, which means bringing it back round to you

**Comment by LiveFireExercise** [comment]
no as it is your approximation of me which is created by you and by extension, your personality, turning it back on you

**Comment by NoobBucket** [comment]
but by sheer coincidence your lint failed checks, which makes you = 🤡 either way

**Comment by LiveFireExercise** [comment]
the failed checks are unrelated to my pr and therefore i win

**Comment by NoobBucket** [comment]
but still on your pr

**Comment by LiveFireExercise** [comment]
doesnt matter

**Comment by NoobBucket** [comment]
does

**Comment by LiveFireExercise** [comment]
doesn't. the fail is from the adonis modern theme which is completely unrelated

**Comment by LiveFireExercise** [comment]
now

**Comment by Sceleratis** [comment]
Make sure updates to settings include an equal update to default settings.

**Pull request closed without merging**
