### PR TITLE
Change the name of ;dex to ;olddex and change the name of ;newdex to dex

### PR DESCRIPTION
**Pull request by KittyTheDeveloper**
## Why?
I actually want to do this to change the command names, That's actually it, since the new dex is easier to use.

### CODE REVIEW

**Comment by ccuser44** [comment]
This will cause issues
The old dex is there because the new dex has issues.

At least keep newdex as an alias of the new dex too

**Comment by Dimenpsyonal** [comment]
Yes atm we're waiting for some updates to newdex before we switch them over

**Comment by DrewBokman** [comment]
you forgot to make a new branch for your fazbear theme, the pr's kinda merged into one

**Comment by KittyTheDeveloper** [comment]
yeah ig i'il close this.

**Pull request closed without merging**
