### PR TITLE
Make givepoints an alias

### PR DESCRIPTION
**Pull request by ccuser44**
Superseeds #1285

Givepoints is deprecated, this adds backwards compatibility

### CODE REVIEW

**Comment by Dimenpsyonal** [comment]
sadface :(
Will probably merge when Proof of Functionality is given

**Comment by ccuser44** [comment]
> sadface :( Will probably merge when Proof of Functionality is given

Works the same as before expect it doesnt show up in suggestions

**Comment by ccuser44** [comment]
Proof of functionality:
image

**Comment by Dimenpsyonal** [comment]
can you also attach proof that the playerpoints gui shows up

**Comment by ccuser44** [comment]
> can you also attach proof that the playerpoints gui shows up

Yes there is no reason it wouldn't if it calls the same pointservice function with the same args

**Comment by Dimenpsyonal** [comment]
True

**Pull request merged**
