### PR TITLE
Adds name argument to :starterscript; Adds :starterscripts; Adds :removestarterscript <name>

### PR DESCRIPTION
**Pull request by SuperCater**
This mostly just adds a way to remove starterscripts

List of everything this adds:
- adds :createstarterscript as another name for :starterscript
- adds :starterscripts using a list UI
- adds :removestarterscript <name>

:removestarterscript also supports an "all" argument which removes all scripts

### CODE REVIEW

**Comment by Dimenpsyonal** [comment]
Interesting

**Comment by watameln** [comment]
but why

**Comment by SuperCater** [comment]
> but why

From my experience makes it easier to manage them. You could already create multiple with :starterscript this just allows you to name them and remove them (since from what i saw you couldn't do that before without using :serverscript)

**Comment by watameln** [comment]
> > but why
> 
> From my experience makes it easier to manage them. You could already create multiple with :starterscript this just allows you to name them and remove them (since from what i saw you couldn't do that before without using :serverscript)

oh sorry for the late reply you ended up in my spam folder, Understood what this is for now

**Comment by Dimenpsyonal** [comment]
needs proof of functionality

**Comment by SuperCater** [comment]
[Proof of Functionality](https://streamable.com/b9b9jc)

**Review by Dimenpsyonal — APPROVED** [review]

**Comment by Dimenpsyonal** [comment]
!rebase

**Comment by Dimenpsyonal** [comment]
:rebase

**Pull request merged**
