### PR TITLE
Fix command quotes showing up in other args

### LINKED ISSUE #1660: Command quote args leave quotes in other args
### Version channel

Nightly

### Loader version

Nightly

### What part of Adonis is this related to?

Command

### What happened?

Original issue: [Issue with " "](https://discord.com/channels/81902207070380032/1206552383123881984/1206552383123881984)

Quotes are sometimes included in the other args. There may be more fundamental underlying issues too.

The code responsible is https://github.com/Epix-Incorporated/Adonis/blob/master/MainModule/Server/Core/Functions.luau#L1311

### Steps to reproduce

1. Run `:cm "Test1" "Test2"

### Device

Windows

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by WalkerOfBacon**
Fixes #1660

PoF:
image
image

### CODE REVIEW

**Comment by Dimenpsyonal** [comment]
stupidly simple fix grr...

**Comment by WalkerOfBacon** [comment]
> stupidly simple fix grr...

IKR

**Comment by ccuser44** [comment]
@Dimenpsyonal This likely breaks nightly arg handling
image

**Comment by WalkerOfBacon** [comment]
> @Dimenpsyonal This likely breaks nightly arg handling image

how tf

**Comment by ccuser44** [comment]
> > @Dimenpsyonal This likely breaks nightly arg handling image
> 
> how tf

I ran `:sm Sample text`

Try to see if it happens on your side (might just be a mistake on my side) but I suspect not

**Comment by WalkerOfBacon** [comment]
I think I fixed it
gonna make a pr rn

**Comment by WalkerOfBacon** [comment]
nvm

**Comment by ccuser44** [comment]
Did the bug happen on your side too?

**Comment by WalkerOfBacon** [comment]
Yeah

Something in this code is not right and im not sure what it is
```luau
if #tab>=num then
    break
elseif #tab>=num-1 then
    table.insert(tab,string.sub(msg,#str+3,#msg))
    continue
end```

**Comment by WalkerOfBacon** [comment]
getting somewhere
image
image

although now theres this random space before it which can still break the arg handling
image

**Comment by WalkerOfBacon** [comment]
unless it doesnt and im just worrying for no reason

**Pull request merged**
