### PR TITLE
Implement a global restart system.

### PR DESCRIPTION
**Pull request by RadiantUwU**
Creates commands to allow restarting all servers. Can be used after an update is deployed as an example.

### CODE REVIEW

**Review by ccuser44 — APPROVED** [review]
You can also just do `:crosserver restart <reason>`

**Comment by moo1210** [comment]
https://devforum.roblox.com/t/automatically-reconnect-to-experiences-during-updates/2866485

**Comment by RadiantUwU** [comment]
> https://devforum.roblox.com/t/automatically-reconnect-to-experiences-during-updates/2866485

This could be enhanced to have countdowns too, please wait a mo.

**Comment by RadiantUwU** [comment]
Yeahhhh definitely squash and merge this

**Comment by RadiantUwU** [comment]
Or if needed i can squash it myself

**Comment by RadiantUwU** [comment]
Alright i'll perform the squashing

**Pull request merged**
