### PR TITLE
Remove :cut command

### PR DESCRIPTION
**Pull request by PurpleCreativity**
No one uses it, it adds "blood" to your game, which roblox could get mad about (i know the blood effect is shit but this is roblox we're talking about)

also i dont really see anything "fun" about theoretically cutting a roblox player and making them bleed

(i dont believe removing a command that doesn't integrate with anything else in adonis requires proof of functionality)

### CODE REVIEW

**Comment by PurpleCreativity** [comment]
also the code is shit 😄👍

**Comment by Dimenpsyonal** [comment]
are you just trying to get contributor

**Comment by PurpleCreativity** [comment]
no one of my friends suggested this so i pr'd it i dont think this deserves contributor lmao

**Comment by PurpleCreativity** [comment]
code is ancient + the idea behind it is creepy (at least in my opinion)

**Comment by Dimenpsyonal** [comment]
i agree

**Comment by PurpleCreativity** [comment]
ill get contributor another way, soon...

**Comment by PurpleCreativity** [comment]
@Dimenpsyonal i haven't contributed to open source before can i delete my fork when this gets merged

**Comment by Dimenpsyonal** [comment]
yea probably

**Comment by P3tray** [comment]
> @Dimenpsyonal i haven't contributed to open source before can i delete my fork when this gets merged

Yes, you can. But it gives you free code flex.

**Comment by P3tray** [comment]
> I can flex how much i've contributed with removing a few lines

Contributed? You've detracted from Adonis. Thank you for your help.

**Pull request merged**
