### PR TITLE
Stop people from easily changing DefaultTheme 

### PR DESCRIPTION
**Pull request by P3tray**
This causes unintended side effects for those who cannot be bothered to read or do not understand my confusing comment.

### CODE REVIEW

**Comment by P3tray** [comment]
i self certify that this pr is a massive w

**Comment by javajuicer** [comment]
why

**Comment by ccuser44** [comment]
Just add a comment warning to not change it

**Comment by P3tray** [comment]
> why

Because you don't know what it does.

**Comment by P3tray** [comment]
> Just add a comment warning to not change it

"unintended side effects for those who cannot be bothered to read"

My solution prevents this, plus I've already done it, this isn't hill worth fighting on because it literally doesn't matter.

**Comment by P3tray** [comment]
> Merge conflicts. Skill issue.

your gonna have to fix them

**Comment by Dimenpsyonal** [comment]
no im not going near the command line again

**Comment by PurpleCreativity** [comment]
it doesn't bite

**Comment by P3tray** [comment]
> no im not going near the command line again

they are 1 liner edits in two files. just copy paste my edits into master and close this and i'll rebase my fork because right now i cant sync with adonis master

**Review by ccuser44 — APPROVED** [review]

**Comment by javajuicer** [comment]
what's wrong with changing defaulttheme?

**Comment by P3tray** [comment]
> what's wrong with changing defaulttheme?

What do you think it does, out of interest?

**Comment by javajuicer** [comment]
> > what's wrong with changing defaulttheme?
> 
> What do you think it does, out of interest?

change the default theme

**Comment by ccuser44** [comment]
> > > what's wrong with changing defaulttheme?
> > 
> > What do you think it does, out of interest?
> 
> change the default theme

Tell him @P3tray

**Comment by P3tray** [comment]
> > > what's wrong with changing defaulttheme?
> > 
> > 
> > What do you think it does, out of interest?
> 
> change the default theme

WRONG!!! SO FOOLISH OF YOU TO ASSUME SUCH A FACT!!! IT, IN FACT, DOES NOT DO SUCH A THING, FOR THAT... well yeah it kinda does do that BUT THAT DOESN'T MATTER, FOR YOUR VAGUE ANSWER IMPLIES THAT YOU REALLY DON'T KNOW WHAT IT DOES! HAVE YOU EVEN READ THE COMMENT BY IT? DOES IT MAKE SENSE TO YOU? NO? I DON'T UNDERSTAND IT EITHER; AND I AM THE ONE WHO WROTE IT!

**Comment by javajuicer** [comment]
> > > > what's wrong with changing defaulttheme?
> > > 
> > > 
> > > What do you think it does, out of interest?
> > 
> > 
> > change the default theme
> 
> WRONG!!! SO FOOLISH OF YOU TO ASSUME SUCH A FACT!!! IT, IN FACT, DOES NOT DO SUCH A THING, FOR THAT... well yeah it kinda does do that BUT THAT DOESN'T MATTER, FOR YOUR VAGUE ANSWER IMPLIES THAT YOU REALLY DON'T KNOW WHAT IT DOES! HAVE YOU EVEN READ THE COMMENT BY IT? DOES IT MAKE SENSE TO YOU? NO? I DON'T UNDERSTAND IT EITHER; AND I AM THE ONE WHO WROTE IT!

that's kind of skibidi sigma. that really has rizz. it's very amongus sus.

**Comment by P3tray** [comment]
> > > > > what's wrong with changing defaulttheme?
> > > > 
> > > > 
> > > > What do you think it does, out of interest?
> > > 
> > > 
> > > change the default theme
> > 
> > 
> > WRONG!!! SO FOOLISH OF YOU TO ASSUME SUCH A FACT!!! IT, IN FACT, DOES NOT DO SUCH A THING, FOR THAT... well yeah it kinda does do that BUT THAT DOESN'T MATTER, FOR YOUR VAGUE ANSWER IMPLIES THAT YOU REALLY DON'T KNOW WHAT IT DOES! HAVE YOU EVEN READ THE COMMENT BY IT? DOES IT MAKE SENSE TO YOU? NO? I DON'T UNDERSTAND IT EITHER; AND I AM THE ONE WHO WROTE IT!
> 
> that's kind of skibidi sigma. that really has rizz. it's very amongus sus.

fanum tax moment. i stuck out my gyatt for the rizzler. baby gronk rainbow friends PR. cameraman comments.

**Pull request closed without merging**
