### PR TITLE
Make FPS gui display player ping

### PR DESCRIPTION
**Pull request by ccuser44**
This is quite useful and the FPS gui is not that useful on it's own so this adds more justification for it to exist

### CODE REVIEW

**Comment by Dimenpsyonal** [comment]
Isn't this why we have a !ping command

**Comment by ccuser44** [comment]
> Isn't this why we have a !ping command

Maybe the two should be merged?

**Comment by Dimenpsyonal** [comment]
They do different things though

**Comment by ccuser44** [comment]
> They do different things though

Many performance GUIs show both

**Comment by Dimenpsyonal** [comment]
Like what

**Comment by ccuser44** [comment]
Closed for later decisions

Potentially a performance stats command should replace both

**Pull request closed without merging**
