### PR TITLE
Add fallback module to loader

### PR DESCRIPTION
**Pull request by joritochip**

### CODE REVIEW

**Comment by ccuser44** [comment]
This might cause some issues because the mainmodule includes parts and models

**Comment by joritochip** [comment]
> This might cause some issues because the mainmodule includes parts and models

I'm not sure how that would cause any issues

**Comment by Sceleratis** [comment]
was it an issue lol

**Comment by joritochip** [comment]
> was it an issue lol

Doing this will cause all of the assets in the Dependencies folder to appear upon insertion into Workspace, which may not be desired behavior... not sure if that is something we should fix or if it should just be considered a nonissue

**Comment by Sceleratis** [comment]
> > was it an issue lol
> 
> Doing this will cause all of the assets in the Dependencies folder to appear upon insertion into Workspace, which may not be desired behavior... not sure if that is something we should fix (also not sure how we would fix it if we wanted to) or if it should just be considered a nonissue

Yeah. I think it might be a non-issue similar to the thumbnail. It might be worth moving all models and parts to be off to the sides of the thumbnail so they are at least all together. Tbh tho, should be in SSS anyway.

**Comment by Sceleratis** [comment]
Wish there was a way to choose where it gets inserted but unfortunately only option for that is plugins

**Comment by P3tray** [comment]
> Wish there was a way to choose where it gets inserted but unfortunately only option for that is plugins

But you can choose the scale of the items, and the positioning relative to the thumbnail. You can also specify where the loader and it's components inserted to when dragged from the toolbox. One half may be in workspace, the other half may be in SS, or all in SSS as it should be.

**Comment by DimensionalFusion** [comment]
Can you fix the conflicts mr jorito

**Comment by P3tray** [comment]
> Can you fix the conflicts mr jorito

Sir this needs closing.

**Comment by P3tray** [comment]
SO SORRY MA'AM

> > Can you fix the conflicts mr jorito
> 
> Sir this needs closing.

SO SORRY I MENT MA'AM

**Review by P3tray — CHANGES_REQUESTED** [review]
requesting that this should be closed.

**Comment by joritochip** [comment]
oops I didn't mean to close this but whatever

**Comment by P3tray** [comment]
> oops I didn't mean to close this but whatever

It was never going to work, anyway.

**Pull request closed without merging**
