### PR TITLE
Re-save UI files to convert old properties to new ones to fix Rojo issues

### PR DESCRIPTION
**Pull request by karl-police**
**DO THIS ONE FIRST:** https://github.com/Epix-Incorporated/Adonis/pull/1177

Re-save UI files to convert old properties to new ones to fix Rojo issues

Same as this https://github.com/Epix-Incorporated/Adonis/pull/1173

but this time I re-saved the correct ones

@Sceleratis merge it in a few minutes I'll add the other files

sorry

### CODE REVIEW

**Comment by LiveFireExercise** [comment]
why do you need to mention scelly bones on every pull request smh

**Comment by karl-police** [comment]
> why do you need to mention scelly bones on every pull request smh

I need merge

he the only one left

**Comment by Expertcoderz** [comment]
image

Welp, we've got conflicts now. Trying to figure out what's going on here.

**Comment by LiveFireExercise** [comment]
Obviously this is your fault smh

**Comment by karl-police** [comment]
I manually fixed the issues just to see that all I had to do is to merge master into the patch.

**Comment by karl-police** [comment]
> I manually resolved all the conflicts just to see that all I had to do is to merge master into the patch.

it's fine now @Expertcoderz

**Comment by karl-police** [comment]
@Expertcoderz

**Pull request merged**
