### PR TITLE
Add back legacy themes (Steampunk and TransBlack)

### PR DESCRIPTION
**Pull request by EasternBloxxer**
The return of the best.
(@LolloDev5123 you suck. (#409))
The themes should now mostly support the new UI features.

### CODE REVIEW

**Comment by EasternBloxxer** [comment]
Btw needs some more testing

**Comment by EasternBloxxer** [comment]
image

**Comment by watameln** [comment]
I want to eat a spray can of paint

**Comment by Dimenpsyonal** [comment]
why

**Comment by spearmintroblox** [comment]
Ok, but why

**Comment by Dimenpsyonal** [comment]
because theyre epic

**Comment by spearmintroblox** [comment]
Why is this needed

**Comment by Dimenpsyonal** [comment]
because theyre cool

**Comment by spearmintroblox** [comment]
I suppose

**Comment by Dimenpsyonal** [comment]
Gonna put this as draft until it's 100% ready cuz UI

**Comment by spearmintroblox** [comment]
I suppose these themes would be nice, idk (I don't remember them tbh)

**Comment by spearmintroblox** [comment]
Yeah, they should be added back

**Comment by Dimenpsyonal** [comment]
I agree

**Comment by EasternBloxxer** [comment]
Ye i will likely be doing hydris too or whatever that one theme was called

**Comment by Dimenpsyonal** [comment]
Excellent, when will this PR be working so I can merge it

**Comment by EasternBloxxer** [comment]
> Excellent, when will this PR be working so I can merge it

Hello, I am Grincher. This PR will be working when I'm done with it. Grincher.

**Comment by Dimenpsyonal** [comment]
Thanks grincher

**Comment by Dimenpsyonal** [comment]
Ngl I kinda forgot what the themes look like

**Comment by EasternBloxxer** [comment]
https://www.roblox.com/games/15151577366/ has the themes

**Comment by Dimenpsyonal** [comment]
excellent

**Comment by EasternBloxxer** [comment]
egg

**Comment by EasternBloxxer** [comment]
Something  Broke :(

**Comment by Dimenpsyonal** [comment]
RIP

**Comment by LolloDev5123** [comment]
Literally 1984

**Comment by Dimenpsyonal** [comment]
LGTM

**Pull request merged**
