### PR TITLE
Remove Client/Local script functions

### PR DESCRIPTION
**Pull request by LiveFireExercise**
can't believe roblox is FORCING this on INNOCENT developers

### CODE REVIEW

**Comment by ccuser44** [comment]
Why do the functions have to be removed? They didn't ask to remove the functions just remove the bytecode interpreter

Theres no good reason to remove said functions

Even if they don't work because there is no LBI a dev can add an LBI back via a plugin to make them work

**Comment by Sceleratis** [comment]
I'm more inclined to just disabled the code execution setting by default since assuming their reasoning is legitimate and not just designed to be an arbitrary pain (which, it's roblox, so realistically the latter) it should suffice given that the interpreter would be unusable unless the place owner explicitly toggles the setting to allow it, indicating with absolute certainty that they want it.

**Comment by ccuser44** [comment]
An alternate fix is done so this pull can be closes.

**Comment by karl-police** [comment]
> An alternate fix is done so this pull can be closes.

I agree, this pull request is scary and there's literally script builder games that let you build scripts so...

**Pull request closed without merging**
