### PR TITLE
Update Settings.lua and DefaultSettings.lua

### PR DESCRIPTION
**Pull request by NoobBucket**

### CODE REVIEW

**Comment by NoobBucket** [comment]
good luck to whoever reviews this

**Comment by fxeP1** [comment]
You probably want to also edit `DefaultSettings.lua` inside the MainModule but this also breaks the "Commands" table on Adonis Settings as it will try to index `Settings.Prefix` (which is just a blank table as you're trying to currently set it).

**Comment by NoobBucket** [comment]
damn. that's annoying. has been fixed, as well as changed the default settings

**Review by P3tray — APPROVED** [review]
Doesn't seem to contain hidden malware. Would be worth doing a check against the nightly settings and defaultsettings table to our current release just in case something changed. I have not tested this. Looks good from a brief check.

**Comment by NoobBucket** [comment]
have fully tested it, works fine. the returned table is exactly the same as the old one

**Comment by EasternBloxxer** [comment]
I will not be approving of removal of commands. Shit pr. go die.

**Pull request closed without merging**
