### PR TITLE
Add support for in game locale changing

### PR DESCRIPTION
**Pull request by ccuser44**
This adds support for <https://devforum.roblox.com/t/localization-api-update-for-upcoming-in-experience-language-switcher/1974795>

### CODE REVIEW

**Comment by LiveFireExercise** [comment]
Ok

**Comment by ccuser44** [comment]
> Does it interfere with a developer's game that tries to do what you're doing?

No

**Comment by karl-police** [comment]
> > Does it interfere with a developer's game that tries to do what you're doing?
> 
> No

Okay ☺

**Comment by ccuser44** [comment]
> Oh wait does this make it so that Adonis's language changes?

Yes

> I didn't even know there are translations on Adonis.

No

**Pull request merged**
