### PR TITLE
Added a chair intolerance to :massbring.

### PR DESCRIPTION
**Pull request by P3tray**
image

### CODE REVIEW

**Comment by P3tray** [comment]
You can now only bring people. You can no longer bring their chairs.

**Review by DimensionalFusion — APPROVED** [review]
wow what a great pull request

**Comment by P3tray** [comment]
Did not test these changes. Shit could quite possibly hit the fan. Regardless, there's no reason it should not work.

**Review by FungusGenerator — APPROVED** [review]
finally good fix

**Comment by P3tray** [comment]
Two people have given a nod to a wall of fan-shit mayhem.

**Comment by P3tray** [comment]
Let the chaos begin, Lord Bushman.

**Comment by Sceleratis** [comment]
Looks like it should work so good enough for me but do please test in the nightly

**Comment by Sceleratls** [comment]
This change broke the :ban command on Adonis. As such, I'm now marking this pull request as null and void. Please contact me thru the Adonis WeChat Group for more information.

**Pull request merged**
