### PR TITLE
Fazbear Theme

### PR DESCRIPTION
**Pull request by KittyTheDeveloper**
# Fazbear Theme
this unsilly github included my other PR "Change ;dex to ;olddex and ;newdex to ;dex"
i don't really use github that much tbh.
Commits since May 2 are the ones i want to contribute..

this is a silly theme btw, i understand if it doesn't get added.

## SCREENSHOTS:
image
## User Panel
image
## Help Button: (beautiful)
image
## Console: (ugly)
image
## Message:
image
image

This took like 1 day to do all the stuff 😭

### CODE REVIEW

**Comment by SuperCater** [comment]
LOL? I really like the colors but not sure about the help button.

**Comment by KittyTheDeveloper** [comment]
> this has the newdex command name changes in it due to being in the same branch

Yeah, sadly couldn't figure out.

**Comment by KittyTheDeveloper** [comment]
> LOL? I really like the colors but not sure about the help button.

Help button is pro.😡😡😡😡😡

**Comment by Dimenpsyonal** [comment]
no

**Comment by KittyTheDeveloper** [comment]
> no

you are breaking my heart 💔

**Comment by Dimenpsyonal** [comment]
good 💔

**Comment by KittyTheDeveloper** [comment]
> good 💔

i spent me life makeing that theme and yu just "no"???? 💔💔💔💔💔💔💔💔💔💔

**Comment by Dimenpsyonal** [comment]
yeah pretty much

**Comment by KittyTheDeveloper** [comment]
> yeah pretty much

💔

**Comment by Dimenpsyonal** [comment]
Maybe u should add it in the adonis themes area idk

**Comment by KittyTheDeveloper** [comment]
> Maybe u should add it in the adonis themes area idk

WHERE?

**Comment by Dimenpsyonal** [comment]
in the discord server, #i-did-a-thing

**Comment by Dimenpsyonal** [comment]
use a plugin theme smh

**Comment by Gr3enTheBlaze** [comment]
>:( KITR THEME GONE NOOOOOOOOOOOOOOOOOOOO

**Comment by Gr3enTheBlaze** [comment]
I partition for a redraw request as the theme is the best tbh.

**Comment by Dimenpsyonal** [comment]
no

**Comment by Gr3enTheBlaze** [comment]
yes 🧌

**Pull request closed without merging**
