### PR TITLE
Add more TextChatService functionality

### PR DESCRIPTION
**Pull request by coasterteam**
Adds support for:
- CanSend mutes (doesn't need to use the ShouldDeliverCallback in TCS)
- :chatnotify works with TextChatService
- :broadcast works with TextChatService
- Both broadcast/chatnotify escape text as well

### CODE REVIEW

**Comment by karl-police** [comment]
ooooo

**Comment by karl-police** [comment]
@coasterteam NO WAIT

DON'T DO IT YET

DON'T DO IT, YOU'RE MODIFYING oh damn
now we lost

**Comment by karl-police** [comment]
You should revert defaultsettings or there's prolly gonna be conflict errors

**Comment by coasterteam** [comment]
Is there a conflict with another pull?

**Comment by karl-police** [comment]
> Is there a conflict with another pull?

yeah, this should explain

https://github.com/Epix-Incorporated/Adonis/pull/1190

**Comment by coasterteam** [comment]
Checking it out, thanks.

**Comment by coasterteam** [comment]
Should be fixed now, https://github.com/Epix-Incorporated/Adonis/commit/3a55061d6ab2d3f0c4b04f46b91301358e2f31d0

**Pull request merged**
