### PR TITLE
MADE MORE LISTS SELECTABLE

### PR DESCRIPTION
**Pull request by EasternBloxxer**
If issue, blame/contact @purple_creativity

### CODE REVIEW

**Comment by EasternBloxxer** [comment]
@purplecreativity

**Comment by PurpleCreativity** [comment]
to join this conversation on GitHub. Already have an account? [Sign in to comment](https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2FEpix-Incorporated%2FAdonis%2Fpull%2F1566)

**Comment by EasternBloxxer** [comment]
> to join this conversation on GitHub. Already have an account? [Sign in to comment](https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2FEpix-Incorporated%2FAdonis%2Fpull%2F1566)

Thank's will do. 

to join this conversation on GitHub. Already have an account? [Sign in to comment](https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2FEpix-Incorporated%2FAdonis%2Fpull%2F1566)

**Comment by PurpleCreativity** [comment]
Lint check failed

**Comment by PurpleCreativity** [comment]
Now this aint getting approved buddy...

**Comment by EasternBloxxer** [comment]
TERRORISM

**Comment by EasternBloxxer** [comment]
if it doesnt pass im gonna go into a maintainers account and merge it myself because idc and because i cvan

**Comment by EasternBloxxer** [comment]
IT PASSED! @PurpleCreativity

**Comment by PurpleCreativity** [comment]
terrorist

**Comment by Dimenpsyonal** [comment]
Ok.

**Pull request merged**
