### PR TITLE
Update Settings.lua and DefaultSettings.lua

### PR DESCRIPTION
**Pull request by NoobBucket**
Changed the layout to make it easier to read, small tweaks to comment wordings, general tidy-up. All works, returned table is the same as the old one.

### CODE REVIEW

**Comment by joritochip** [comment]
Closing, since all this PR really does is remove all of the documentation for each config option

**Comment by LiveFireExercise** [comment]
why the long spaces between different settings
isn't two lines a bit much

**Comment by NoobBucket** [comment]
it makes a consistent spacing between the settings for ones that only have one comment under it compared to two. it's more visually pleasing

**Comment by watameln** [comment]
splash splash im taking a bath

**Comment by LiveFireExercise** [comment]
yeah but it makes it like 1000 lines long

**Comment by NoobBucket** [comment]
which is nothing compared to literally every other script in adonis

**Comment by LiveFireExercise** [comment]
but this script is one that basically all adonis users interact with, thus condensing it is key 🔑

**Comment by NoobBucket** [comment]
> one that basically all adonis users interact with

which is why it needs to be good, clear, and easily understandable without giving people a headache while they read it

**Comment by LiveFireExercise** [comment]
which is why almost 0 effort is needed when accessing the script, not scrolling a million lines

**Comment by NoobBucket** [comment]
its not even that long, and requires 0 effort. if people think its effort to read through it, then they are efforting about effort

**Comment by LiveFireExercise** [comment]
a thousand is a very big number. a thousand lines is very long.

**Comment by LiveFireExercise** [comment]
please do immediately.

**Comment by NoobBucket** [comment]
then will you approve????? 😍

**Comment by LiveFireExercise** [comment]
no i still need my pull request

**Comment by LiveFireExercise** [comment]
no you

**Comment by watameln** [comment]
stop sending me fucking emails 😠

**Comment by LiveFireExercise** [comment]
i agree. this is going on my blog

**Comment by NoobBucket** [comment]
> stop sending me fucking emails 😠

make me

> no you

mine has a green tick, yours has a red cross. the end

**Pull request closed without merging**
