### PR TITLE
Windows 11 theme

### PR DESCRIPTION
**Pull request by LiveFireExercise**
Pretty much that.

Includes:

- ## ❕Notifications

Screenshot 2023-04-09 at 12 29 31

- ## 👨‍💻Command line
Screenshot 2023-04-09 at 12 30 22

- ## 🪟Window (get it? windows?? haha xd)

Screenshot 2023-04-09 at 12 30 40

- ## 🧐Topbar hints

Screenshot 2023-04-09 at 12 33 32

### CODE REVIEW

**Review by LiveFireExercise — COMMENTED** [review]
10/10 i approve

**Comment by xhayper** [comment]
0/10, windows xp is better

**Comment by LiveFireExercise** [comment]
i think you missed out a 1 before the 0

**Comment by xhayper** [comment]
Are you sure?

**Comment by LiveFireExercise** [comment]
Yes 100%, it is impossible to dislike this theme

**Comment by LiveFireExercise** [comment]
(I made it)

**Comment by xhayper** [comment]
0/10

**Comment by LiveFireExercise** [comment]
*10/10

**Comment by xhayper** [comment]
***0/10

**Comment by LiveFireExercise** [comment]
*****10/10

**Comment by NoobBucket** [comment]
yall it's 10/100

**Comment by LiveFireExercise** [comment]
*100/10

**Comment by xhayper** [comment]
*********0/10

**Comment by xhayper** [comment]
nooooooooooo.... its zero out of ten

**Comment by WalkerOfBacon** [comment]
Sorry meant to put 10/10

**Comment by LiveFireExercise** [comment]
> nooooooooooo.... its zero out of ten

you are clearly wrong as this theme is 100% perfect and there is nothing wrong with it. therefore ten out of ten

**Comment by LiveFireExercise** [comment]
lint is cringe pay no attention to its cringeness

**Comment by WalkerOfBacon** [comment]
Quick question, what does it look like when you use :n

**Comment by LiveFireExercise** [comment]
> Quick question, what does it look like when you use :n

very good

**Comment by WalkerOfBacon** [comment]
@LiveFireExercise may I see it

**Comment by LiveFireExercise** [comment]
> @LiveFireExercise may I see it

i can’t show, just download it and add it to your adonis

**Review by WalkerOfBacon — CHANGES_REQUESTED** [review]
Remove `SystemTitle` from the following lines as it returns an error when using it

```local SystemTitle = frame2.SystemTitle```
```SystemTitle = settings.SystemTitle```

**Comment by joritochip** [comment]
do we really need another theme

**Comment by LiveFireExercise** [comment]
> do we really need another theme

why not, who is it hurting

**Comment by LiveFireExercise** [comment]
there are 0 things wrong with the theme therefore it is impossible for it to get a 0/10

**Comment by xhayper** [comment]
> there are 0 things wrong with the theme therefore it is impossible for it to get a 0/10

you're wrong

**Comment by watameln** [comment]
🐈

**Comment by LiveFireExercise** [comment]
> > there are 0 things wrong with the theme therefore it is impossible for it to get a 0/10
> 
> you're wrong

prove it

**Comment by xhayper** [comment]
a

**Comment by joritochip** [comment]
please stop spamming comments i dont want to get an email every time one of you posts an emoji for no reason

**Comment by watameln** [comment]
🤓

**Comment by Expertcoderz** [comment]
Cool idea; however, the implementation quality requires some working on, IMO, before becoming a built-in theme in Adonis.
 
Needs fixing, based on first glance:

1. Text fonts used should be consistent throughout. This includes font sizing; the "Command line" input box's text seems rather too large, for instance.
 
2. The window title text label should appear vertically aligned to the middle.
 
Furthermore, the visual style of UI elements should ideally be tweaked to more authentically resemble that of WinUI controls (as seen in Windows 11's UIs). These include buttons, input boxes, tab buttons, sliders, and more.

One important thing to do would be to incorporate the signature [Mica](https://learn.microsoft.com/en-us/windows/apps/design/style/mica) material into window (and message/notif) backgrounds; perhaps replacing the potentially off-putting wallpaper that is currently shown behind the userpanel window in this theme. Alternatively, if achieving a Mica-like effect isn't feasible: an opaque dark gray background mimicking the state of the Windows 11 UI appearance with "transparency effects" disabled.

In addition, the notification popups can be styled in the form of an actual Windows 11 notification.                                                                                                                              

Lastly, maybe you could change the help button to have it look like the Windows 11 Start button?

**Comment by LiveFireExercise** [comment]
10/10 review, I rate it 10/10

**Comment by LiveFireExercise** [comment]
> Furthermore, the visual style of UI elements should ideally be tweaked to more authentically resemble that of WinUI controls (as seen in Windows 11's UIs). These include buttons, input boxes, tab buttons, sliders, and more.

what does this mean

**Comment by LiveFireExercise** [comment]
> One important thing to do would be to incorporate the signature [Mica](https://learn.microsoft.com/en-us/windows/apps/design/style/mica) material into window (and message/notif) backgrounds; perhaps replacing the potentially off-putting wallpaper that is currently shown behind the userpanel window in this theme. Alternatively, if achieving a Mica-like effect isn't feasible: an opaque dark gray background mimicking the state of the Windows 11 UI appearance with "transparency effects" disabled.

that seems like too much of a hassle for a robotic admin system

**Comment by LiveFireExercise** [comment]
> One important thing to do would be to incorporate the signature [Mica](https://learn.microsoft.com/en-us/windows/apps/design/style/mica) material into window (and message/notif) backgrounds; perhaps replacing the potentially off-putting wallpaper that is currently shown behind the userpanel window in this theme. Alternatively, if achieving a Mica-like effect isn't feasible: an opaque dark gray background mimicking the state of the Windows 11 UI appearance with "transparency effects" disabled.

that seems like too much of a hassle for a robotic admin system

**Comment by LiveFireExercise** [comment]
> In addition, the notification popups can be styled in the form of an actual Windows 11 notification.

i tried this, but turns out it’s hard

**Comment by LiveFireExercise** [comment]
> Lastly, maybe you could change the help button to have it look like the Windows 11 Start button?

i will do this when my internet speed becomes greater than 0.2Mbps

**Comment by LiveFireExercise** [comment]
I have decided I can no longer be bothered

**Comment by LiveFireExercise** [comment]
what can I say, expertcoderz just hates it too much

**Pull request closed without merging**
