### PR TITLE
Made dex fetch api dump on server start

### PR DESCRIPTION
**Pull request by EasternBloxxer**
The dex server plugin code should be way cleaner now and easier to edit
Dex now also fetches api dump on server start so it doesn't have to be manually updated whenever roblox adds something new

image

### CODE REVIEW

**Comment by EasternBloxxer** [comment]
Highlight will come in a different PR.

**Comment by Dimenpsyonal** [comment]
why did you delete old Dex

**Comment by EasternBloxxer** [comment]
why would you use the old dex its only more laggier and broken

**Comment by Dimenpsyonal** [comment]
yea but you didnt change the commands as well

**Comment by EasternBloxxer** [comment]
yes i did

**Pull request merged**
