### PR TITLE
Updated v240 changelog

### PR DESCRIPTION
**Pull request by ccuser44**
This makes the v240 changelog have all the newer pulls and changes. Also this fixes some of the older changelogs.

Anyways I think it's a good time to update to v240 after it's checked that there are no breaking bugs.

One thing to remember scel (or the person who publishes an Adonis update) is that you don't load the file in studio because Robloxes new font system will mess up Adonises font sizes so upload it directly with Rojo or tarmac.

### CODE REVIEW

**Comment by LiveFireExercise** [comment]
this is my job 😠

**Comment by watameln** [comment]
u type liek cat mrrp 🐈

**Comment by LiveFireExercise** [comment]
:3

**Comment by watameln** [comment]
⚡⚡⚡

**Comment by xhayper** [comment]
it is too perfect

**Pull request merged**
