### PR TITLE
It's a number not a string

### PR DESCRIPTION
**Pull request by ccuser44**
Change string to number

### CODE REVIEW

**Comment by Dimenpsyonal** [comment]
I tested it with == "inf" in studio and it worked just fine

**Comment by ccuser44** [comment]
> I tested it with == "inf" in studio and it worked just fine

I wouldn't rely on it
It's not even clear if it actually works

**Comment by Dimenpsyonal** [comment]
Screenshot 2024-01-22 at 21 18 30
u didnt delete the section...

**Comment by ccuser44** [comment]
> Screenshot 2024-01-22 at 21 18 30 u didnt delete the section...

Done

**Pull request merged**
