### PR TITLE
Added in-game Script Editor

### PR DESCRIPTION
**Pull request by kaiserandaxl**
# Added script editor
This script editor is one of the first to be put into adonis (or the first) and it is kind of complex, not really tho.

Showcase:
image

https://cdn.discordapp.com/attachments/772798498835398659/1188596469058519190/2023-12-24_15-35-51.mp4?ex=659b19b9&is=6588a4b9&hm=0a13fa1ddaa8e16735602f165b44b79c420f1059671452508386518e904a8657&

### CODE REVIEW

**Comment by watameln** [comment]
wasnt this a thing before

**Comment by kaiserandaxl** [comment]
> wasnt this a thing before

Scriptbuilder is a thing, but it's shit

**Comment by watameln** [comment]
delete scriptbuilder then

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Comment by watameln** [comment]
oh fuck my life

my shit is buggin

**Comment by moo1210** [comment]
Do you approve these changes?

**Review by EasternBloxxer — APPROVED** [review]

**Comment by watameln** [comment]
> Do you approve these changes?

um

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Review by watameln — APPROVED** [review]

**Comment by watameln** [comment]
yes

**Comment by SuperCater** [comment]
Would be cool if there was a :scripteditor list operation

this is really cool tho

**Review by SuperCater — APPROVED** [review]

**Comment by SuperCater** [comment]
Im not that experienced with how the remote module works but shouldnt these remotes have like some type of permission check for security since it allows code execution? Or does Adonis do that already somehow

**Comment by kaiserandaxl** [comment]
@SuperCater

The only script that calls that is in the script editor UI. The only way to get access to the UI is by running the command blocked by Creator Level Admin. Some people might say well if they use :guiview they have access, but when a user does that no code can run by pressing any buttons meaning to even have access to using the remote you need first to get access to the ScriptEditor which in turn needs Creator Perms, on top of that the remote looks for scripts made by the player who called the remote menaing if somebody Hijacked it they'd still be unable to execute code without first having a script which they need Creator to run.

**Comment by kaiserandaxl** [comment]
The check was a feature to purposefully built in, but was a feature to store different scripts according to each player which added a built-in security feature that one can't bypass unless they can manually update a table stored with-in Variables

**Review by ccuser44 — CHANGES_REQUESTED** [review]
This should be integrated with scriptbuilder

Or at least make it use scriptbuilder under the hood

**Comment by kaiserandaxl** [comment]
> This should be integrated with scriptbuilder
> 
> Or at least make it use scriptbuilder under the hood

I'm not gonna integrate it with script builder. And I can't make it use script builder under the hood since the coding for script builder sucks.

The reason I'm not integrating it into script builder is: script builder is for small things to have fun, and the script editor is to actually script things.

**Comment by ccuser44** [comment]
> > This should be integrated with scriptbuilder
> > Or at least make it use scriptbuilder under the hood
> 
> I'm not gonna integrate it with script builder. And I can't make it use script builder under the hood since the coding for script builder sucks.
> 
> The reason I'm not integrating it into script builder is: script builder is for small things to have fun, and the script editor is to actually script things.

I don't see why not
You could just make the editor save/upload scripts to scriptbuilder and the run to run a scriptbuilder script. Don't see what's wrong with it?

**Comment by kaiserandaxl** [comment]
> > > This should be integrated with scriptbuilder
> > > Or at least make it use scriptbuilder under the hood
> > 
> > 
> > I'm not gonna integrate it with script builder. And I can't make it use script builder under the hood since the coding for script builder sucks.
> > The reason I'm not integrating it into script builder is: script builder is for small things to have fun, and the script editor is to actually script things.
> 
> I don't see why not You could just make the editor save/upload scripts to scriptbuilder and the run to run a scriptbuilder script. Don't see what's wrong with it?

Also, script builder saves differently and I'd rather not do all the changes to please one person when it works completely fine, if it ain't broke don't fix it.

**Comment by ccuser44** [comment]
> > > This should be integrated with scriptbuilder
> > > Or at least make it use scriptbuilder under the hood
> > 
> > 
> > I'm not gonna integrate it with script builder. And I can't make it use script builder under the hood since the coding for script builder sucks.
> > The reason I'm not integrating it into script builder is: script builder is for small things to have fun, and the script editor is to actually script things.
> 
> ~I don't see why not~ ~You could just make the editor save/upload scripts to scriptbuilder and the run to run a scriptbuilder script. Don't see what's wrong with it?~

You know what nvm it's fine as is

**Pull request merged**
