### PR TITLE
Fix `:removecamera` not working

### PR DESCRIPTION
**Pull request by ccuser44**
Fix `:removecamera` not working

### CODE REVIEW

**Comment by Dimenpsyonal** [comment]
when fix autotriage

**Comment by ccuser44** [comment]
> when fix autotriage

I already did. It should be working :shrug:

**Comment by Dimenpsyonal** [comment]
then why is it failing

**Comment by ccuser44** [comment]
Its likely a permission error preventing the workflow from adding the tag.

**Comment by Dimenpsyonal** [comment]
Run github/issue-labeler@v3.4
Configuration file (path: .github/labeler.yml) does not exist locally, fetching via the API
Could not add label(s) ⌛needs PoF to issue #1746
Error: AggregateError

**Comment by ccuser44** [comment]
Aha, it was a permissions issue:
[image](https://github.com/github/issue-labeler/issues/80#issuecomment-1869546259)

**Comment by ccuser44** [comment]
PoF:
image

**Pull request merged**
