### PR TITLE
Client/Core code readability improvements

### PR DESCRIPTION
**Pull request by RoyallyFlushed**
* Transitioned Client/Core codebase from wait(), spawn() & defer() to task lib implementation
* Renamed unused variables in for loop declaration to _ convention in Client/Core codebase
* Removed all instances of pairs(), ipairs() and next() from Client/Core codebase
* Transitioned Client/Core codebase from old increment, decrement & self concat to shorthand (+=, -=, ..=)

### CODE REVIEW

**Comment by Expertcoderz** [comment]
> * Transitioned Client/Core codebase from wait(), spawn() & defer() to task lib implementation

Eh that's kinda useless since they all already use the task library internally (it's set in the script env).
``wait = task.wait``

**Review by Expertcoderz — APPROVED** [review]

**Comment by RoyallyFlushed** [comment]
Ah, I do apologise, I should have double checked. Although I do think it might be a little confusing to maintain using that method.

**Comment by LolloDev5123** [comment]
This is the highest quality PR I've ever seen
LGTM!

**Comment by RoyallyFlushed** [comment]
> This is the highest quality PR I've ever seen LGTM!

I presume sarcasm? lmao I am new to github so I am making a lot of mistakes it seems.

**Comment by LolloDev5123** [comment]
You labelled the commits correctly, your description features all the changes, the fact that you are new to GitHub makes you less careless like other PRs

**Comment by RoyallyFlushed** [comment]
> You labelled the commits correctly, your description features all the changes, the fact that you are new to GitHub makes you less careless like other PRs

Well I really appreciate that! I try to be as descriptive as possible! Thanks for your kind words!!

**Pull request merged**
