### PR TITLE
Create Adonis Critical Incident fallback

### PR DESCRIPTION
**Pull request by NoobBucket**

### CODE REVIEW

**Comment by ccuser44** [comment]
What is this exactly for?

**Comment by alau740** [comment]
> What is this exactly for?

the idea with this is that if for some reason, the adonis mainmodule is not available, we load a version of adonis with minimal features so that basic functionality will still work (it can still load admins/banned users, etc)

this way it will stop banned users from re-entering games they were banned from

**Comment by LiveFireExercise** [comment]
This was supposed to be merged back in may to the fallback branch. it is now august

**Comment by moo1210** [comment]
'major' label seems really fitting...

**Comment by LiveFireExercise** [comment]
Can you fix the merge conflicts pls thx

**Pull request closed without merging**
