### PR TITLE
Fix SetFPS and RestoreFPS

### PR DESCRIPTION
**Pull request by watameln**
it works trust me

### CODE REVIEW

**Comment by watameln** [comment]
merge pwease i tested it works fine

**Comment by LiveFireExercise** [comment]
Are you dure

**Comment by watameln** [comment]
> Are you sure

yes

**Comment by watameln** [comment]
doesn't work well with games with memory checks

**Comment by watameln** [comment]
@Expertcoderz please don't add "bug" to this. it's not a bug. its code no insects no nothin

**Comment by Expertcoderz** [comment]
> @Expertcoderz please don't add "bug" to this. it's not a bug. its code no insects no nothin

you're the bug.

**Comment by watameln** [comment]
> you're the bug.

this is true.

**Comment by watameln** [comment]
merge @LiveFireExercise 🐱

**Comment by LiveFireExercise** [comment]
Failing rojo...

**Comment by watameln** [comment]
> Failing rojo...

fix it

**Comment by LiveFireExercise** [comment]
YOU fix it!!!
Run rojo build -o Adonis_Nightly_2023-10-24.rbxm .github/build.project.json
/home/runner/work/_temp/51be284c-3cb4-4155-8508-f2baac606f65.sh: line 1: rojo: command not found

**Comment by watameln** [comment]
> YOU fix it!!! Run rojo build -o Adonis_Nightly_2023-10-24.rbxm .github/build.project.json /home/runner/work/_temp/51be284c-3cb4-4155-8508-f2baac606f65.sh: line 1: rojo: command not found

update rojo its outdated

**Pull request merged**
