### PR TITLE
Fix chargear not working in r6

### PR DESCRIPTION
**Pull request by WalkerOfBacon**
running :chargear as r6 doesn't work because BodyHeightScale, BodyDepthScale, and BodyWidthScale does not exist.

### CODE REVIEW

**Review by ccuser44 — CHANGES_REQUESTED** [review]
I don't think you should just disable this for R6. What you should do is use the internal Adonis scaling function for R6 instead

**Comment by WalkerOfBacon** [comment]
> I don't think you should just disable this for R6. What you should do is use the internal Adonis scaling function for R6 instead

Ill try

**Comment by WalkerOfBacon** [comment]
I kinda did it
image

**Comment by WalkerOfBacon** [comment]
well now I did it
image
however I keep picking it up once I backspace it

**Comment by WalkerOfBacon** [comment]
nvm I found the problem

**Comment by WalkerOfBacon** [comment]
I did it

**Comment by WalkerOfBacon** [comment]
I hope you guys dont mind a smaller character

**Comment by ccuser44** [comment]
There is an internal Adonis scaling function that the `:size` command uses. No need to implement is customly

**Comment by WalkerOfBacon** [comment]
> There is an internal Adonis scaling function that the `:size` command uses. No need to implement is customly

That would require resizing the player which I dont really wanna do

**Comment by WalkerOfBacon** [comment]
And even if I did use it, the player would hold in the gear incorrectly (from a bunch of testing I did).

**Comment by WalkerOfBacon** [comment]
I needed to fix the position of the gear so that way the player looks like its holding it

**Pull request merged**
