### PR TITLE
HttpEnabled view

### PR DESCRIPTION
**Pull request by ocelot81**
switched from sending a request to google to built-in HttpEnabled

### CODE REVIEW

**Comment by ocelot81** [comment]
m what failed now

**Comment by Dimenpsyonal** [comment]
we tried this and it didn't work cuz roblox hadn't enabled it fully. has this changed

**Comment by ocelot81** [comment]
misclick closed on mobile, roblox moment

**Comment by Dimenpsyonal** [comment]
but does it work?!?!?!

**Comment by ocelot81** [comment]
I think it should be rolled out fully by now but not sure, ill keep this open and check later or wait for someone thatd confirm

**Comment by ocelot81** [comment]
not on computer rn

**Comment by ocelot81** [comment]
ok confirmed it works on my machine in studio for opting out in game settings

**Comment by Dimenpsyonal** [comment]
does it work in not studio though

**Comment by ocelot81** [comment]
ya

**Pull request merged**
