### PR TITLE
Use string interpolation in favor of concatenation

### PR DESCRIPTION
**Pull request by Redfuire**
I've cleaned up some code to use string interpolation instead of concatenation. Additionally, I have modified the server-side anti-cheat and removed the explicit calls to `tostring`, which I don't think is necessary since it should be called automatically.

### CODE REVIEW

**Comment by LiveFireExercise** [comment]
NOOOOOO

**Review by moo1210 — APPROVED** [review]
🙏

**Comment by ccuser44** [comment]
This is not better because string.format is used under the hood so it might be more expensivw and aöl tooling isnt supported

**Comment by moo1210** [comment]
What, Lol? First, it does get lowered into string.format calls and tostring calls internally (see [the Luau RFC](https://github.com/Roblox/luau/blob/master/rfcs/syntax-string-interpolation.md)), but that would not make it "more expensive" in any meaningful way. Even if we were trying to do pointless micro-optimizations like such that mean literally nothing because they only save less than a nanosecond when they're all combined, the newer method is probably faster realistically speaking. Secondly, what is "aöl" tooling???

**Comment by watameln** [comment]
> NOOOOOO

stop crying on github. my dms exist for a reason

**Comment by moo1210** [comment]
> What I mean is introducing unnecessary Luau syntax isn't good
And string interpolation is not necessary

Why, and why..? This project only runs on Luau and already uses luau syntax elsewhere, I don’t know what backward compatibility with Lua 5.1 matters to us.
 Also saying updates  are ‘not necessary’ means effectively nothing.

**Comment by LiveFireExercise** [comment]
concatenation >>> interpolation

**Review by Expertcoderz — APPROVED** [review]

**Pull request merged**
