### PR TITLE
Move `UseLinkedListsInLogs` from Settings to Variables

### PR DESCRIPTION
**Pull request by ccuser44**
I don't think it makes sense to have this in the settings file as it's not that important. If people want to change it they can make a plugin to change a flag in the variables file.

### CODE REVIEW

**Comment by Dimenpsyonal** [comment]
Hmm idk about this one chief

**Comment by ccuser44** [comment]
> Hmm idk about this one chief

Does it really need to be in the settings. We don't have a setting for GoodSignal. (Probably Coasterteam is the right person to answer this because he added the LinkedList)

**Comment by Dimenpsyonal** [comment]
@coasterteam thoughts on this

**Comment by Dimenpsyonal** [comment]
Yeah actually this seems like a better idea than in settings

**Pull request merged**
