### PR TITLE
Update copyright year for 2024

### PR DESCRIPTION
**Pull request by P3tray**
I have not tested these changes in Roblox as I believe I am above the law.

### CODE REVIEW

**Review by watameln — CHANGES_REQUESTED** [review]
please update to 2025

**Comment by P3tray** [comment]
> please update to 2025

image

**Comment by watameln** [comment]
> > please update to 2025
> 
> image

thomas brown

**Review by moo1210 — CHANGES_REQUESTED** [review]
The year isn't 2024.

**Comment by P3tray** [comment]
> > > please update to 2025
> > 
> > 
> > image
> 
> thomas brown

NAME LEAK 2024 [UNREAL]

**Comment by P3tray** [comment]
> The year isn't 2024.

Yuh huh

**Comment by ccuser44** [comment]
The date should be the date of publish not the current year

**Comment by P3tray** [comment]
> The date should be the date of publish not the current year

🤓

How about 2016-2024 (c) Sceleratis [whatever]

**Comment by Dimenpsyonal** [comment]
> The date should be the date of publish not the current year

but roblox says copyright 2024. did roblox release in 2024???

**Pull request merged**
