### PR TITLE
Remove deprecated fonts

### PR DESCRIPTION
**Pull request by Dimenpsyonal**
Replace instances of Arial and Gotham with Source Sans and Ubuntu, respectively

### CODE REVIEW

**Comment by Dimenpsyonal** [comment]
All Arial and Gotham replacements should be done now
PR on hiatus until Roblox tells us more

**Comment by LolloDev5123** [comment]
Replace Gotham with Montserrat as recommended by Roblox, Ubuntu ruins everything that had Gotham

**Comment by Dimenpsyonal** [comment]
I think it looks better.

**Comment by P3tray** [comment]
If you don't change them they get autoredirected to whatever Roblox decides is best in the future. Sounds like a better solution to me.

**Comment by Dimenpsyonal** [comment]
k

**Pull request closed without merging**
