### PR TITLE
chore: codebase cleanup

### PR DESCRIPTION
**Pull request by xhayper**
- [ ] String interpolation merged into roblox stable
- [x] Server side script
- [x] Client side script
- [ ] Commands

### CODE REVIEW

**Comment by WaviestBalloon** [comment]
No lint 👁️

**Comment by LiveFireExercise** [comment]
I hate lint WaviestBalloon

**Comment by WaviestBalloon** [comment]
I hate lint pbstFusion

**Comment by LiveFireExercise** [comment]
I hate lint WaviestBalloon

**Comment by WaviestBalloon** [comment]
I hate lint pbstFusion

**Comment by WaviestBalloon** [comment]
@xhayper can you potentially remove the `nil` command, it was broken in a Roblox update and has never been removed from Adonis since.
I believe the issue was already reported in the Adonis Discord server and nothing can really be done about it.

image

**Comment by xhayper** [comment]
ok

**Comment by WaviestBalloon** [comment]
> ok

chad

**Comment by ccuser44** [comment]
I think this pull should be broken up into multiple pull requests to mske merging easier

**Comment by P3tray** [comment]
> @xhayper can you potentially remove the `nil` command, it was broken in a Roblox update and has never been removed from Adonis since. I believe the issue was already reported in the Adonis Discord server and nothing can really be done about it.
> 
> image

@xhayper do not remove `:nil`. I use it constantly regardless if Roblox no longer allows clients with a nil player object.

**Comment by WaviestBalloon** [comment]
> @xhayper do not remove `:nil`. I use it constantly regardless if Roblox no longer allows clients with a nil player object.

image

**Comment by xhayper** [comment]
Gonna close this PR, it will be much better idea to just create multiple PR for this.

**Pull request closed without merging**
