### PR TITLE
Tabelise settings

### PR DESCRIPTION
**Pull request by LiveFireExercise**
This time featuring default settings!

### CODE REVIEW

**Comment by P3tray** [comment]
about time

**Comment by LiveFireExercise** [comment]
Ikr

**Comment by WalkerOfBacon** [comment]
oh wow

image

**Comment by LiveFireExercise** [comment]
what the heck is a table constructor element

**Comment by WalkerOfBacon** [comment]
Idek

Also there is multiple errors in here too
Line 237 to 637
image

**Comment by LiveFireExercise** [comment]
i have no idea why thats happening

**Comment by watameln** [comment]
> what the heck is a table constructor element

https://www.lua.org/pil/3.6.html

**Comment by WalkerOfBacon** [comment]
A main chunk of it was duplicates

**Comment by LiveFireExercise** [comment]
so whats wrong with it

**Comment by WalkerOfBacon** [comment]
Im currently trying to figure it out

**Comment by WalkerOfBacon** [comment]
image
image

**Comment by LiveFireExercise** [comment]
What

**Comment by WalkerOfBacon** [comment]
Both says "Unknown global"

**Comment by LiveFireExercise** [comment]
so fix it then

**Comment by watameln** [comment]
image

Missing `;`

**Comment by LiveFireExercise** [comment]
i appear to have missed that out

**Comment by watameln** [comment]
so silli cat

**Comment by LiveFireExercise** [comment]
get a new pull request merged silly cat

**Comment by karl-police** [comment]
@Expertcoderz Undo this.

I saw this change before, but I actually never commented here it seems like.

I don't like this.

&nbsp;

People told me things like:
It saves characters 😄

that's the only thing about it.

This causes the same old issues, with worser cons.

https://github.com/Epix-Incorporated/Adonis/commit/492b8f30095e57bbbbd661fd74e4fff517083e4f
This was a great fix.

It prevent stuff that is happening right now.
image


the automatic shifting thing
image


It's no longer convenient anymore.

The settings doesn't only contain the settings, but descs and order.
I think order was already as a plain table style. It didn't even need more, because the key are just numbers.

But settings and descs are not.

The settings are pretty big
image

If you scroll into the nowhere. How can I figure out what "MaxLogs" is part of? I'd have to scroll up to see, "Ah it's part of ``settings``".

&nbsp;

The next annoying this is, because it's in a table, you're forced to add a ``,`` or ``;`` at the end.
Look at where the ``;`` for this long string is at.
image


Do you see the distance, I had to travel with the scroll bar?

Even the Pull requester, had troubles adding the ``;`` everywhere.

&nbsp;

That's not the only issue.
image

This.

```lua
local v1 = {
  hello = "Hello";
  whatIsHello = v1.hello
}

-- damn I can't access v1
```

This is what bytecode decompilers do, when it has troubles figuring out stuff. Often metatables or something. So, someone has to go over it and manually fix it.

```lua
local v1 = {}
v1.hello
v1.whatIsHello = v1.hello
```

&nbsp;

I actually wonder @Sceleratis or @Expertcoderz opinion about this style.
It's just https://github.com/Epix-Incorporated/Adonis/pull/1152
while I think there were pro and cons in that. But I think there's not even one GitHub link left, for someone to even confirm that this is the official repository now.

Thing is it also removed that there's a documentation. While.. well it's there but it was never finished so it don't even matter anyways.

But is this just removing stuff, to save more characters. While Google just has to add 1 new data storage slot and they added 1 Billion Bytes that cover like multiple years of whatever anyone is trying to save.

And we just save space, without caring about what effects this causes. As example, the mental effects this causes, when someone else edits the code.

And here we're talking about the Settings. Something that someone is most likely going to edit.

**Comment by LiveFireExercise** [comment]
too long didnt read

**Comment by karl-police** [comment]
short summarized:

doing all this to remove settings and all other table names infront of the table keys just to save data:

without the care of what mental chaos this caused


There's no way. Someone prefers this

```lua
local settings = {

-- 500 lines later
    whereAmI = "I don't know, but I hope I am still at Settings. Here's some extra string stuff so the semicolon is far away";
}
```

Over this
```lua
settings.whereAmI = "Oh I know I am in settings"
```

in this context

**Pull request merged**
