### PR TITLE
Revert regressions introduced in #1313 and #1308

### PR DESCRIPTION
**Pull request by ccuser44**
## Notice
Please make sure you read the Contributing Guidelines before submitting a pull request. https://github.com/Epix-Incorporated/Adonis/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by Dimenpsyonal** [comment]
Why is this a regression exactly

**Comment by ccuser44** [comment]
> Why is this a regression exactly

It undid the conversion to a newer function for unknown reasons

**Comment by Dimenpsyonal** [comment]
I thought MakeGui was the newer function

**Comment by ccuser44** [comment]
> I thought MakeGui was the newer function

It's not

**Pull request merged**
