### PR TITLE
Add a healthlist command

### PR DESCRIPTION
**Pull request by Lethalitics**
It is currently difficult to tell which players are godded, have altered health, etc. This command makes an automatically updating list of all players and their respective healths. Players are ordered first by max health, then current health, then display name, then username.

### CODE REVIEW

**Comment by Lethalitics** [comment]
Screen Shot 2022-08-01 at 3 31 57 AM

Ui layout

**Comment by Expertcoderz** [comment]
Sounds similar to the ``:players`` command.

**Comment by Expertcoderz** [comment]
- Use ``service.FormatPlayer`` for displaying player names.
- Use ``character:FindFirstChildOfClass("Humanoid")`` instead of ``character.Humanoid`` since Humanoids may not be named "Humanoid".

**Comment by Expertcoderz** [comment]
Epic.

**Pull request merged**
